<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Page.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $com_jpgk_common_rpc__t_ParamsMap;

if(!isset($com_jpgk_common_rpc__t_ParamsMap))
{
    $com_jpgk_common_rpc__t_ParamsMap = IcePHP_defineDictionary('::com::jpgk::common::rpc::ParamsMap', $IcePHP__t_string, $IcePHP__t_string);
}

global $com_jpgk_common_rpc__t_Page;

if(!class_exists('com_jpgk_common_rpc_Page'))
{
    class com_jpgk_common_rpc_Page
    {
        public function __construct($pageNum=0, $pageSize=0, $pageTotal=0, $totalNum=0, $params=null)
        {
            $this->pageNum = $pageNum;
            $this->pageSize = $pageSize;
            $this->pageTotal = $pageTotal;
            $this->totalNum = $totalNum;
            $this->params = $params;
        }

        public function __toString()
        {
            global $com_jpgk_common_rpc__t_Page;
            return IcePHP_stringify($this, $com_jpgk_common_rpc__t_Page);
        }

        public $pageNum;
        public $pageSize;
        public $pageTotal;
        public $totalNum;
        public $params;
    }

    $com_jpgk_common_rpc__t_Page = IcePHP_defineStruct('::com::jpgk::common::rpc::Page', 'com_jpgk_common_rpc_Page', array(
        array('pageNum', $IcePHP__t_int), 
        array('pageSize', $IcePHP__t_int), 
        array('pageTotal', $IcePHP__t_int), 
        array('totalNum', $IcePHP__t_int), 
        array('params', $com_jpgk_common_rpc__t_ParamsMap)));
}
?>
