<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `Comment.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once "Ice.php";
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';
require_once APP_PATH.'Common/Lib/Ice/Page.php';
require_once APP_PATH.'Common/Lib/Ice/clientphp/model/UCenter.php';
require_once APP_PATH.'Common/Lib/Ice/clientphp/model/CommentClass.php';

global $com_jpgk_catering_rpc_comment__t_V0324CommentModel;
global $com_jpgk_catering_rpc_comment__t_V0324CommentModelPrx;

if(!class_exists('com_jpgk_catering_rpc_comment_V0324CommentModel'))
{
    class com_jpgk_catering_rpc_comment_V0324CommentModel extends com_jpgk_catering_rpc_comment_CommentModel
    {
        public function __construct($id=0, $uid=0, $app=com_jpgk_catering_rpc_comment_CommentApp::News, $mod='', $rowId=0, $content='', $createTime=0, $status=0, $area='', $title='', $user=null, $support=false, $supportNum=0, $pid=0, $commentReplys=null, $userV0324=null)
        {
            parent::__construct($id, $uid, $app, $mod, $rowId, $content, $createTime, $status, $area, $title, $user, $support, $supportNum, $pid, $commentReplys);
            $this->userV0324 = $userV0324;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::V0324CommentModel';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_comment__t_V0324CommentModel;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_comment__t_V0324CommentModel);
        }

        public $userV0324;
    }

    class com_jpgk_catering_rpc_comment_V0324CommentModelPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::comment::V0324CommentModel', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::comment::V0324CommentModel', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::V0324CommentModel';
        }
    }

    $com_jpgk_catering_rpc_comment__t_V0324CommentModel = IcePHP_declareClass('::com::jpgk::catering::rpc::comment::V0324CommentModel');
    $com_jpgk_catering_rpc_comment__t_V0324CommentModelPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::comment::V0324CommentModel');

    $com_jpgk_catering_rpc_comment__t_V0324CommentModel = IcePHP_defineClass('::com::jpgk::catering::rpc::comment::V0324CommentModel', 'com_jpgk_catering_rpc_comment_V0324CommentModel', -1, false, false, $com_jpgk_catering_rpc_comment__t_CommentModel, null, array(
        array('userV0324', $com_jpgk_catering_rpc_ucenter__t_V0324Userinfo, false, 0)));

    $com_jpgk_catering_rpc_comment__t_V0324CommentModelPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_comment__t_V0324CommentModel);
}

global $com_jpgk_catering_rpc_comment__t_V0324CommentSeq;

if(!isset($com_jpgk_catering_rpc_comment__t_V0324CommentSeq))
{
    $com_jpgk_catering_rpc_comment__t_V0324CommentSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::comment::V0324CommentSeq', $com_jpgk_catering_rpc_comment__t_V0324CommentModel);
}

global $com_jpgk_catering_rpc_comment__t_CommentService;
global $com_jpgk_catering_rpc_comment__t_CommentServicePrx;

if(!interface_exists('com_jpgk_catering_rpc_comment_CommentService'))
{
    interface com_jpgk_catering_rpc_comment_CommentService extends com_jpgk_common_rpc_BaseService
    {
        public function getCommentDetailByAppV0324($uid, $app, $id);
        public function getCommentListByAppV0324($uid, $app, $rowId, $page, $outPage);
        public function getCommentListByApp($user, $app, $rowId, $page, $outPage);
        public function getCommentDetailByApp($user, $app, $id);
        public function getCommentListByUserApp($user, $page, $outPage);
        public function saveComment($comment);
        public function support($rowId, $app, $user);
        public function deleteUserComment($commentId, $userId, $app);
    }

    class com_jpgk_catering_rpc_comment_CommentServicePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::comment::CommentService', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::comment::CommentService', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::CommentService';
        }
    }

    $com_jpgk_catering_rpc_comment__t_CommentService = IcePHP_defineClass('::com::jpgk::catering::rpc::comment::CommentService', 'com_jpgk_catering_rpc_comment_CommentService', -1, true, false, $Ice__t_Object, array($com_jpgk_common_rpc__t_BaseService), null);

    $com_jpgk_catering_rpc_comment__t_CommentServicePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_comment__t_CommentService);

    IcePHP_defineOperation($com_jpgk_catering_rpc_comment__t_CommentService, 'getCommentDetailByAppV0324', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_comment__t_CommentApp, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_comment__t_V0324CommentModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_comment__t_CommentService, 'getCommentListByAppV0324', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_comment__t_CommentApp, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_common_rpc__t_Page, false, 0)), array(array($com_jpgk_common_rpc__t_Page, false, 0)), array($com_jpgk_catering_rpc_comment__t_V0324CommentSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_comment__t_CommentService, 'getCommentListByApp', 0, 0, 0, array(array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_catering_rpc_comment__t_CommentApp, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_common_rpc__t_Page, false, 0)), array(array($com_jpgk_common_rpc__t_Page, false, 0)), array($com_jpgk_catering_rpc_comment__t_CommentSeq, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_comment__t_CommentService, 'getCommentDetailByApp', 0, 0, 0, array(array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_catering_rpc_comment__t_CommentApp, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_comment__t_CommentModel, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_comment__t_CommentService, 'getCommentListByUserApp', 0, 0, 0, array(array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_common_rpc__t_Page, false, 0)), array(array($com_jpgk_common_rpc__t_Page, false, 0)), array($com_jpgk_catering_rpc_comment__t_CommentSeq, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_comment__t_CommentService, 'saveComment', 0, 0, 0, array(array($com_jpgk_catering_rpc_comment__t_CommentSaveModel, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_comment__t_CommentService, 'support', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_comment__t_CommentApp, false, 0), array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0)), null, array($IcePHP__t_bool, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_comment__t_CommentService, 'deleteUserComment', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_comment__t_CommentApp, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
}
?>
