<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `BaseException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $com_jpgk_common_rpc__t_BaseError;

if(!class_exists('com_jpgk_common_rpc_BaseError'))
{
    class com_jpgk_common_rpc_BaseError extends Ice_UserException
    {
        public function __construct($reason='', $userMessage='')
        {
            $this->reason = $reason;
            $this->userMessage = $userMessage;
        }

        public function ice_name()
        {
            return 'com::jpgk::common::rpc::BaseError';
        }

        public function __toString()
        {
            global $com_jpgk_common_rpc__t_BaseError;
            return IcePHP_stringifyException($this, $com_jpgk_common_rpc__t_BaseError);
        }

        public $reason;
        public $userMessage;
    }

    $com_jpgk_common_rpc__t_BaseError = IcePHP_defineException('::com::jpgk::common::rpc::BaseError', 'com_jpgk_common_rpc_BaseError', false, null, array(
        array('reason', $IcePHP__t_string, false, 0),
        array('userMessage', $IcePHP__t_string, false, 0)));
}

global $com_jpgk_common_rpc__t_BaseException;

if(!class_exists('com_jpgk_common_rpc_BaseException'))
{
    class com_jpgk_common_rpc_BaseException extends Ice_UserException
    {
        public function __construct($reason='', $userMessage='')
        {
            $this->reason = $reason;
            $this->userMessage = $userMessage;
        }

        public function ice_name()
        {
            return 'com::jpgk::common::rpc::BaseException';
        }

        public function __toString()
        {
            global $com_jpgk_common_rpc__t_BaseException;
            return IcePHP_stringifyException($this, $com_jpgk_common_rpc__t_BaseException);
        }

        public $reason;
        public $userMessage;
    }

    $com_jpgk_common_rpc__t_BaseException = IcePHP_defineException('::com::jpgk::common::rpc::BaseException', 'com_jpgk_common_rpc_BaseException', false, null, array(
        array('reason', $IcePHP__t_string, false, 0),
        array('userMessage', $IcePHP__t_string, false, 0)));
}

global $com_jpgk_common_rpc__t_NullValueException;

if(!class_exists('com_jpgk_common_rpc_NullValueException'))
{
    class com_jpgk_common_rpc_NullValueException extends com_jpgk_common_rpc_BaseException
    {
        public function __construct($reason='', $userMessage='')
        {
            parent::__construct($reason, $userMessage);
        }

        public function ice_name()
        {
            return 'com::jpgk::common::rpc::NullValueException';
        }

        public function __toString()
        {
            global $com_jpgk_common_rpc__t_NullValueException;
            return IcePHP_stringifyException($this, $com_jpgk_common_rpc__t_NullValueException);
        }
    }

    $com_jpgk_common_rpc__t_NullValueException = IcePHP_defineException('::com::jpgk::common::rpc::NullValueException', 'com_jpgk_common_rpc_NullValueException', false, $com_jpgk_common_rpc__t_BaseException, null);
}
?>
