<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `SecondhandMarket.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once "Ice.php";
require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';
require_once APP_PATH.'Common/Lib/Ice/Page.php';
require_once APP_PATH.'Common/Lib/Ice/common.php';
require_once 'model/SecondMarketHandClass.php';

global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020;
global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020Prx;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_GoodsV171020'))
{
    class com_jpgk_catering_rpc_secondhandmarket_GoodsV171020 extends com_jpgk_catering_rpc_secondhandmarket_Goods
    {
        public function __construct($goodsId=0, $title='', $description='', $goodsCategory=null, $salePrice=0.0, $boughtPrice=0.0, $view=0, $messageUserNum=0, $linkPhone='', $linkName='', $province=0, $city=0, $districtText='', $startTime=0, $endTime=0, $status=0, $checkStatus=0, $isCollected=0, $checkUid=0, $createTime=0, $showCreateTime='', $pictures=null, $isTop=0, $goodsStatus='', $maintenanceSupport=0)
        {
            parent::__construct($goodsId, $title, $description, $goodsCategory, $salePrice, $boughtPrice, $view, $messageUserNum, $linkPhone, $linkName, $province, $city, $districtText, $startTime, $endTime, $status, $checkStatus, $isCollected, $checkUid, $createTime, $showCreateTime, $pictures, $isTop, $goodsStatus);
            $this->maintenanceSupport = $maintenanceSupport;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::GoodsV171020';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020);
        }

        public $maintenanceSupport;
    }

    class com_jpgk_catering_rpc_secondhandmarket_GoodsV171020PrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::GoodsV171020', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::GoodsV171020', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::GoodsV171020';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020 = IcePHP_declareClass('::com::jpgk::catering::rpc::secondhandmarket::GoodsV171020');
    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020Prx = IcePHP_declareProxy('::com::jpgk::catering::rpc::secondhandmarket::GoodsV171020');

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020 = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::GoodsV171020', 'com_jpgk_catering_rpc_secondhandmarket_GoodsV171020', -1, false, false, $com_jpgk_catering_rpc_secondhandmarket__t_Goods, null, array(
        array('maintenanceSupport', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020Prx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService;
global $com_jpgk_catering_rpc_secondhandmarket__t_SecondHandServicePrx;

if(!interface_exists('com_jpgk_catering_rpc_secondhandmarket_SecondHandService'))
{
    interface com_jpgk_catering_rpc_secondhandmarket_SecondHandService extends com_jpgk_common_rpc_BaseService
    {
        public function getDistrictsHasGoods($pid);
        public function getGoodsList($page, $outPage);
        public function getGoodsListByDistAndCategory($title, $provinceId, $cityId, $categoryId, $goodsSort, $page, $outPage);
        public function getGoodsCategoryListByPId($pId);
        public function getGoods($id, $userId);
        public function getGoodsV171020($id, $userId);
        public function getGoodsDetail($id, $userId);
        public function getUserGoods($userId);
        public function getSmsContentTemp();
        public function getSuggestedGoodses($categoryId, $excludedGoodsId);
        public function viewGoods($goodsId);
        public function publishOrEditGoods($goodsSaveModel);
        public function deleteOrRecoverGoods($goodsId, $status);
        public function getUserCollectGoods($userId);
        public function checkOrder($userId);
        public function confirmOrder($userId, $deliveryId, $payType, $remark);
        public function weChatPay($orderId);
        public function aLiPay($orderId);
        public function getUserOrders($userId, $orderStatus);
        public function getOrder($orderId);
        public function getMaintenance($goodsId);
        public function updateOrderStatus($orderId, $orderStatus);
    }

    class com_jpgk_catering_rpc_secondhandmarket_SecondHandServicePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::SecondHandService', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::SecondHandService', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::SecondHandService';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::SecondHandService', 'com_jpgk_catering_rpc_secondhandmarket_SecondHandService', -1, true, false, $Ice__t_Object, array($com_jpgk_common_rpc__t_BaseService), null);

    $com_jpgk_catering_rpc_secondhandmarket__t_SecondHandServicePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService);

    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getDistrictsHasGoods', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_common__t_DistrictSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getGoodsList', 0, 0, 0, array(array($com_jpgk_common_rpc__t_Page, false, 0)), array(array($com_jpgk_common_rpc__t_Page, false, 0)), array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getGoodsListByDistAndCategory', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSort, false, 0), array($com_jpgk_common_rpc__t_Page, false, 0)), array(array($com_jpgk_common_rpc__t_Page, false, 0)), array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getGoodsCategoryListByPId', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategorySeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getGoods', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_Goods, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getGoodsV171020', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsV171020, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getGoodsDetail', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetail, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getUserGoods', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getSmsContentTemp', 0, 0, 0, null, null, array($IcePHP__t_string, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getSuggestedGoodses', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'viewGoods', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, null, null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'publishOrEditGoods', 0, 0, 0, array(array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModel, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'deleteOrRecoverGoods', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getUserCollectGoods', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'checkOrder', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_Order, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'confirmOrder', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_string, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'weChatPay', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'aLiPay', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getUserOrders', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_secondhandmarket__t_OrderStatus, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_OrderSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getOrder', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_Order, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'getMaintenance', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_secondhandmarket__t_Maintenance, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_secondhandmarket__t_SecondHandService, 'updateOrderStatus', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_secondhandmarket__t_OrderStatus, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
}
?>
