<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `SupplyMarketing.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//
require_once "Ice.php";
require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';
require_once APP_PATH.'Common/Lib/Ice/Page.php';
require_once APP_PATH.'Common/Lib/Ice/common.php';
require_once 'model/SupplyMarketingClass.php';

global $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategory;
global $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategoryPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_V0316TopProductCategory'))
{
    class com_jpgk_catering_rpc_supplymarketing_V0316TopProductCategory extends com_jpgk_catering_rpc_supplymarketing_TopProductCategory
    {
        public function __construct($id=0, $name='', $iconUrl='', $productCategorys=null, $products=null)
        {
            parent::__construct($id, $name, $iconUrl, $productCategorys);
            $this->products = $products;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::V0316TopProductCategory';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategory;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategory);
        }

        public $products;
    }

    class com_jpgk_catering_rpc_supplymarketing_V0316TopProductCategoryPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::V0316TopProductCategory', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::V0316TopProductCategory', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::V0316TopProductCategory';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategory = IcePHP_declareClass('::com::jpgk::catering::rpc::supplymarketing::V0316TopProductCategory');
    $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategoryPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::supplymarketing::V0316TopProductCategory');

    $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategory = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::V0316TopProductCategory', 'com_jpgk_catering_rpc_supplymarketing_V0316TopProductCategory', -1, false, false, $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategory, null, array(
        array('products', $com_jpgk_catering_rpc_supplymarketing__t_ProductSeq, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategoryPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategory);
}

global $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategorySeq;

if(!isset($com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategorySeq))
{
    $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategorySeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::supplymarketing::V0316TopProductCategorySeq', $com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategory);
}

global $com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService;
global $com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingServicePrx;

if(!interface_exists('com_jpgk_catering_rpc_supplymarketing_SupplyMarketingService'))
{
    interface com_jpgk_catering_rpc_supplymarketing_SupplyMarketingService extends com_jpgk_common_rpc_BaseService
    {
        public function getDistrictsHasProducts($pid);
        public function getHomeProductCategorys();
        public function getHomeProductCategorysV0316();
        public function getProductCategoryByPId($pId);
        public function getProductList($title, $provinceId, $cityId, $categoryId, $level, $productSort, $page, $outPage);
        public function getProduct($productId, $userId);
        public function getProductDetail($productId, $userId);
        public function getCompany($companyId);
        public function getRelatedProductList($productId, $categoryId);
        public function getCompanyOrtherProductList($productId, $companyId);
        public function appoint($appointment);
        public function getAppointments($userId, $status);
        public function cancelAppointment($userId, $appointmentId);
        public function confirmDeal($userId, $appointmentId);
        public function getHotSearch();
        public function getUserCollectProducts($userId);
    }

    class com_jpgk_catering_rpc_supplymarketing_SupplyMarketingServicePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::SupplyMarketingService', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::SupplyMarketingService', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::SupplyMarketingService';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::SupplyMarketingService', 'com_jpgk_catering_rpc_supplymarketing_SupplyMarketingService', -1, true, false, $Ice__t_Object, array($com_jpgk_common_rpc__t_BaseService), null);

    $com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingServicePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService);

    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getDistrictsHasProducts', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_common__t_DistrictSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getHomeProductCategorys', 0, 0, 0, null, null, array($com_jpgk_catering_rpc_supplymarketing__t_TopProductCategorySeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getHomeProductCategorysV0316', 0, 0, 0, null, null, array($com_jpgk_catering_rpc_supplymarketing__t_V0316TopProductCategorySeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getProductCategoryByPId', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_supplymarketing__t_ProductCategorySeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getProductList', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_supplymarketing__t_ProductSort, false, 0), array($com_jpgk_common_rpc__t_Page, false, 0)), array(array($com_jpgk_common_rpc__t_Page, false, 0)), array($com_jpgk_catering_rpc_supplymarketing__t_ProductSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getProduct', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_supplymarketing__t_Product, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getProductDetail', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_supplymarketing__t_ProductDetail, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getCompany', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_supplymarketing__t_Company, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getRelatedProductList', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_supplymarketing__t_ProductSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getCompanyOrtherProductList', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_supplymarketing__t_ProductSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'appoint', 0, 0, 0, array(array($com_jpgk_catering_rpc_supplymarketing__t_Appointment, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getAppointments', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_supplymarketing__t_AppointmentStatus, false, 0)), null, array($com_jpgk_catering_rpc_supplymarketing__t_AppointmentSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'cancelAppointment', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'confirmDeal', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getHotSearch', 0, 0, 0, null, null, array($com_jpgk_catering_rpc_supplymarketing__t_HotSearchSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_supplymarketing__t_SupplyMarketingService, 'getUserCollectProducts', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_supplymarketing__t_ProductSeq, false, 0), null);
}
?>
