<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `BaseService.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $com_jpgk_common_rpc__t_ByteSeqence;

if(!isset($com_jpgk_common_rpc__t_ByteSeqence))
{
    $com_jpgk_common_rpc__t_ByteSeqence = IcePHP_defineSequence('::com::jpgk::common::rpc::ByteSeqence', $IcePHP__t_byte);
}

global $com_jpgk_common_rpc__t_ShortSeqence;

if(!isset($com_jpgk_common_rpc__t_ShortSeqence))
{
    $com_jpgk_common_rpc__t_ShortSeqence = IcePHP_defineSequence('::com::jpgk::common::rpc::ShortSeqence', $IcePHP__t_short);
}

global $com_jpgk_common_rpc__t_IntSeqence;

if(!isset($com_jpgk_common_rpc__t_IntSeqence))
{
    $com_jpgk_common_rpc__t_IntSeqence = IcePHP_defineSequence('::com::jpgk::common::rpc::IntSeqence', $IcePHP__t_int);
}

global $com_jpgk_common_rpc__t_LongSeqence;

if(!isset($com_jpgk_common_rpc__t_LongSeqence))
{
    $com_jpgk_common_rpc__t_LongSeqence = IcePHP_defineSequence('::com::jpgk::common::rpc::LongSeqence', $IcePHP__t_long);
}

global $com_jpgk_common_rpc__t_DoubleSeqence;

if(!isset($com_jpgk_common_rpc__t_DoubleSeqence))
{
    $com_jpgk_common_rpc__t_DoubleSeqence = IcePHP_defineSequence('::com::jpgk::common::rpc::DoubleSeqence', $IcePHP__t_double);
}

global $com_jpgk_common_rpc__t_FloatSeqence;

if(!isset($com_jpgk_common_rpc__t_FloatSeqence))
{
    $com_jpgk_common_rpc__t_FloatSeqence = IcePHP_defineSequence('::com::jpgk::common::rpc::FloatSeqence', $IcePHP__t_float);
}

global $com_jpgk_common_rpc__t_StringSeqence;

if(!isset($com_jpgk_common_rpc__t_StringSeqence))
{
    $com_jpgk_common_rpc__t_StringSeqence = IcePHP_defineSequence('::com::jpgk::common::rpc::StringSeqence', $IcePHP__t_string);
}

global $com_jpgk_common_rpc__t_IntDictionary;

if(!isset($com_jpgk_common_rpc__t_IntDictionary))
{
    $com_jpgk_common_rpc__t_IntDictionary = IcePHP_defineDictionary('::com::jpgk::common::rpc::IntDictionary', $IcePHP__t_int, $IcePHP__t_int);
}

global $com_jpgk_common_rpc__t_BaseService;
global $com_jpgk_common_rpc__t_BaseServicePrx;

if(!interface_exists('com_jpgk_common_rpc_BaseService'))
{
    interface com_jpgk_common_rpc_BaseService extends Ice_Object
    {
    }

    class com_jpgk_common_rpc_BaseServicePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::common::rpc::BaseService', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::common::rpc::BaseService', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::common::rpc::BaseService';
        }
    }

    $com_jpgk_common_rpc__t_BaseService = IcePHP_defineClass('::com::jpgk::common::rpc::BaseService', 'com_jpgk_common_rpc_BaseService', -1, true, false, $Ice__t_Object, null, null);

    $com_jpgk_common_rpc__t_BaseServicePrx = IcePHP_defineProxy($com_jpgk_common_rpc__t_BaseService);
}
?>
