<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `common.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once "Ice.php";
require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';
require_once APP_PATH.'Common/Lib/Ice/Page.php';
require_once APP_PATH.'Common/Lib/Ice/ResponseModel.php';
require_once APP_PATH.'Common/Lib/Ice/FileSystem.php';
require_once APP_PATH.'Common/Lib/Ice/CommonClass.php';

global $com_jpgk_catering_rpc_common__t_CommonService;
global $com_jpgk_catering_rpc_common__t_CommonServicePrx;

if(!interface_exists('com_jpgk_catering_rpc_common_CommonService'))
{
    interface com_jpgk_catering_rpc_common_CommonService extends com_jpgk_common_rpc_BaseService
    {
        public function getDistrictListByPid($upId);
        public function uploadPicture($uploadModel, $app);
        public function uploadPictureAndBoundRowId($uploadModel, $rowId, $app);
        public function deletePicture($pictureId);
        public function regenerationPicture($pictureId);
        public function collect($userId, $rowId, $app);
        public function cancelCollection($userId, $rowId, $app);
        public function cancelCollections($userId, $rowIds, $app);
        public function share($userId, $rowId, $app);
        public function getUserShareNum($rowId, $app);
        public function checkAppVersion($version, $appType);
        public function getJobs();
        public function contactUs();
        public function getBootAdv();
        public function getBootAdvV2();
        public function getNavigations();
        public function getAppCode();
        public function getUserDeliveryAddresses($uid);
        public function saveOrUpdateDeliveryAddress($deliveryAddress);
        public function setDefaultDeliveryAddress($uid, $deliveryAddressId);
        public function deleteDeliveryAddress($uid, $deliveryAddressId);
    }

    class com_jpgk_catering_rpc_common_CommonServicePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::common::CommonService', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::common::CommonService', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::CommonService';
        }
    }

    $com_jpgk_catering_rpc_common__t_CommonService = IcePHP_defineClass('::com::jpgk::catering::rpc::common::CommonService', 'com_jpgk_catering_rpc_common_CommonService', -1, true, false, $Ice__t_Object, array($com_jpgk_common_rpc__t_BaseService), null);

    $com_jpgk_catering_rpc_common__t_CommonServicePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_common__t_CommonService);

    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'getDistrictListByPid', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_common__t_DistrictSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'uploadPicture', 0, 0, 0, array(array($com_jpgk_FileSystem_rpc__t_UploadModel, false, 0), array($com_jpgk_catering_rpc_common__t_App, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'uploadPictureAndBoundRowId', 0, 0, 0, array(array($com_jpgk_FileSystem_rpc__t_UploadModel, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_common__t_App, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'deletePicture', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'regenerationPicture', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'collect', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_common__t_App, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'cancelCollection', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_common__t_App, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'cancelCollections', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($com_jpgk_common_rpc__t_IntSeqence, false, 0), array($com_jpgk_catering_rpc_common__t_App, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'share', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_common__t_App, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'getUserShareNum', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($com_jpgk_catering_rpc_common__t_App, false, 0)), null, array($IcePHP__t_int, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'checkAppVersion', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($com_jpgk_catering_rpc_common__t_AppType, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'getJobs', 0, 0, 0, null, null, array($com_jpgk_catering_rpc_common__t_JobSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'contactUs', 0, 0, 0, null, null, array($IcePHP__t_string, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'getBootAdv', 0, 0, 0, null, null, array($com_jpgk_catering_rpc_common__t_AdvModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'getBootAdvV2', 0, 0, 0, null, null, array($com_jpgk_catering_rpc_common__t_AdvModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'getNavigations', 0, 0, 0, null, null, array($com_jpgk_catering_rpc_common__t_NavigationSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'getAppCode', 0, 0, 0, null, null, array($IcePHP__t_string, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'getUserDeliveryAddresses', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_common__t_DeliveryAddressSeq, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'saveOrUpdateDeliveryAddress', 0, 0, 0, array(array($com_jpgk_catering_rpc_common__t_DeliveryAddress, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'setDefaultDeliveryAddress', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_common__t_CommonService, 'deleteDeliveryAddress', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
}
?>
