<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `ResponseModel.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $com_jpgk_common_rpc__t_ResponseModel;

if(!class_exists('com_jpgk_common_rpc_ResponseModel'))
{
    class com_jpgk_common_rpc_ResponseModel
    {
        public function __construct($success=false, $status=0, $msg='')
        {
            $this->success = $success;
            $this->status = $status;
            $this->msg = $msg;
        }

        public function __toString()
        {
            global $com_jpgk_common_rpc__t_ResponseModel;
            return IcePHP_stringify($this, $com_jpgk_common_rpc__t_ResponseModel);
        }

        public $success;
        public $status;
        public $msg;
    }

    $com_jpgk_common_rpc__t_ResponseModel = IcePHP_defineStruct('::com::jpgk::common::rpc::ResponseModel', 'com_jpgk_common_rpc_ResponseModel', array(
        array('success', $IcePHP__t_bool), 
        array('status', $IcePHP__t_int), 
        array('msg', $IcePHP__t_string)));
}

global $com_jpgk_common_rpc__t_ResponseModelClass;
global $com_jpgk_common_rpc__t_ResponseModelClassPrx;

if(!class_exists('com_jpgk_common_rpc_ResponseModelClass'))
{
    class com_jpgk_common_rpc_ResponseModelClass extends Ice_ObjectImpl
    {
        public function __construct($success=false, $status=0, $msg='')
        {
            $this->success = $success;
            $this->status = $status;
            $this->msg = $msg;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::common::rpc::ResponseModelClass';
        }

        public function __toString()
        {
            global $com_jpgk_common_rpc__t_ResponseModelClass;
            return IcePHP_stringify($this, $com_jpgk_common_rpc__t_ResponseModelClass);
        }

        public $success;
        public $status;
        public $msg;
    }

    class com_jpgk_common_rpc_ResponseModelClassPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::common::rpc::ResponseModelClass', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::common::rpc::ResponseModelClass', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::common::rpc::ResponseModelClass';
        }
    }

    $com_jpgk_common_rpc__t_ResponseModelClass = IcePHP_defineClass('::com::jpgk::common::rpc::ResponseModelClass', 'com_jpgk_common_rpc_ResponseModelClass', -1, false, false, $Ice__t_Object, null, array(
        array('success', $IcePHP__t_bool, false, 0),
        array('status', $IcePHP__t_int, false, 0),
        array('msg', $IcePHP__t_string, false, 0)));

    $com_jpgk_common_rpc__t_ResponseModelClassPrx = IcePHP_defineProxy($com_jpgk_common_rpc__t_ResponseModelClass);
}
?>
