<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CommonClass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';
require_once APP_PATH.'Common/Lib/Ice/Page.php';
require_once APP_PATH.'Common/Lib/Ice/ResponseModel.php';
require_once APP_PATH.'Common/Lib/Ice/FileSystem.php';

global $com_jpgk_catering_rpc_common__t_App;

if(!class_exists('com_jpgk_catering_rpc_common_App'))
{
    class com_jpgk_catering_rpc_common_App
    {
        const News = 0;
        const Event = 1;
        const Post = 2;
        const Resource = 3;
        const SHM = 4;
        const SupplyMarket = 5;
        const Live = 6;
        const CircleVideo = 7;
    }

    $com_jpgk_catering_rpc_common__t_App = IcePHP_defineEnum('::com::jpgk::catering::rpc::common::App', array('News', 0, 'Event', 1, 'Post', 2, 'Resource', 3, 'SHM', 4, 'SupplyMarket', 5, 'Live', 6, 'CircleVideo', 7));
}

global $com_jpgk_catering_rpc_common__t_Picture;
global $com_jpgk_catering_rpc_common__t_PicturePrx;

if(!class_exists('com_jpgk_catering_rpc_common_Picture'))
{
    class com_jpgk_catering_rpc_common_Picture extends Ice_ObjectImpl
    {
        public function __construct($id=0, $url='', $status=0, $createTime=0)
        {
            $this->id = $id;
            $this->url = $url;
            $this->status = $status;
            $this->createTime = $createTime;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::Picture';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_common__t_Picture;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_common__t_Picture);
        }

        public $id;
        public $url;
        public $status;
        public $createTime;
    }

    class com_jpgk_catering_rpc_common_PicturePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::common::Picture', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::common::Picture', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::Picture';
        }
    }

    $com_jpgk_catering_rpc_common__t_Picture = IcePHP_defineClass('::com::jpgk::catering::rpc::common::Picture', 'com_jpgk_catering_rpc_common_Picture', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('url', $IcePHP__t_string, false, 0),
        array('status', $IcePHP__t_int, false, 0),
        array('createTime', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_common__t_PicturePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_common__t_Picture);
}

global $com_jpgk_catering_rpc_common__t_PictureSeq;

if(!isset($com_jpgk_catering_rpc_common__t_PictureSeq))
{
    $com_jpgk_catering_rpc_common__t_PictureSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::common::PictureSeq', $com_jpgk_catering_rpc_common__t_Picture);
}

global $com_jpgk_catering_rpc_common__t_District;
global $com_jpgk_catering_rpc_common__t_DistrictPrx;

if(!class_exists('com_jpgk_catering_rpc_common_District'))
{
    class com_jpgk_catering_rpc_common_District extends Ice_ObjectImpl
    {
        public function __construct($id=0, $name='', $level=0, $upId=0)
        {
            $this->id = $id;
            $this->name = $name;
            $this->level = $level;
            $this->upId = $upId;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::District';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_common__t_District;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_common__t_District);
        }

        public $id;
        public $name;
        public $level;
        public $upId;
    }

    class com_jpgk_catering_rpc_common_DistrictPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::common::District', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::common::District', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::District';
        }
    }

    $com_jpgk_catering_rpc_common__t_District = IcePHP_defineClass('::com::jpgk::catering::rpc::common::District', 'com_jpgk_catering_rpc_common_District', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('name', $IcePHP__t_string, false, 0),
        array('level', $IcePHP__t_int, false, 0),
        array('upId', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_common__t_DistrictPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_common__t_District);
}

global $com_jpgk_catering_rpc_common__t_DistrictSeq;

if(!isset($com_jpgk_catering_rpc_common__t_DistrictSeq))
{
    $com_jpgk_catering_rpc_common__t_DistrictSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::common::DistrictSeq', $com_jpgk_catering_rpc_common__t_District);
}

global $com_jpgk_catering_rpc_common__t_AppType;

if(!class_exists('com_jpgk_catering_rpc_common_AppType'))
{
    class com_jpgk_catering_rpc_common_AppType
    {
        const Android = 0;
        const IOS = 1;
    }

    $com_jpgk_catering_rpc_common__t_AppType = IcePHP_defineEnum('::com::jpgk::catering::rpc::common::AppType', array('Android', 0, 'IOS', 1));
}

global $com_jpgk_catering_rpc_common__t_Job;
global $com_jpgk_catering_rpc_common__t_JobPrx;

if(!class_exists('com_jpgk_catering_rpc_common_Job'))
{
    class com_jpgk_catering_rpc_common_Job extends Ice_ObjectImpl
    {
        public function __construct($name='', $id=0)
        {
            $this->name = $name;
            $this->id = $id;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::Job';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_common__t_Job;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_common__t_Job);
        }

        public $name;
        public $id;
    }

    class com_jpgk_catering_rpc_common_JobPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::common::Job', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::common::Job', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::Job';
        }
    }

    $com_jpgk_catering_rpc_common__t_Job = IcePHP_defineClass('::com::jpgk::catering::rpc::common::Job', 'com_jpgk_catering_rpc_common_Job', -1, false, false, $Ice__t_Object, null, array(
        array('name', $IcePHP__t_string, false, 0),
        array('id', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_common__t_JobPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_common__t_Job);
}

global $com_jpgk_catering_rpc_common__t_JobSeq;

if(!isset($com_jpgk_catering_rpc_common__t_JobSeq))
{
    $com_jpgk_catering_rpc_common__t_JobSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::common::JobSeq', $com_jpgk_catering_rpc_common__t_Job);
}

global $com_jpgk_catering_rpc_common__t_AdvModel;
global $com_jpgk_catering_rpc_common__t_AdvModelPrx;

if(!class_exists('com_jpgk_catering_rpc_common_AdvModel'))
{
    class com_jpgk_catering_rpc_common_AdvModel extends Ice_ObjectImpl
    {
        public function __construct($title='', $url='', $imagePath='', $countDown=0)
        {
            $this->title = $title;
            $this->url = $url;
            $this->imagePath = $imagePath;
            $this->countDown = $countDown;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::AdvModel';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_common__t_AdvModel;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_common__t_AdvModel);
        }

        public $title;
        public $url;
        public $imagePath;
        public $countDown;
    }

    class com_jpgk_catering_rpc_common_AdvModelPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::common::AdvModel', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::common::AdvModel', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::AdvModel';
        }
    }

    $com_jpgk_catering_rpc_common__t_AdvModel = IcePHP_defineClass('::com::jpgk::catering::rpc::common::AdvModel', 'com_jpgk_catering_rpc_common_AdvModel', -1, false, false, $Ice__t_Object, null, array(
        array('title', $IcePHP__t_string, false, 0),
        array('url', $IcePHP__t_string, false, 0),
        array('imagePath', $IcePHP__t_string, false, 0),
        array('countDown', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_common__t_AdvModelPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_common__t_AdvModel);
}

global $com_jpgk_catering_rpc_common__t_Navigation;
global $com_jpgk_catering_rpc_common__t_NavigationPrx;

if(!class_exists('com_jpgk_catering_rpc_common_Navigation'))
{
    class com_jpgk_catering_rpc_common_Navigation extends Ice_ObjectImpl
    {
        public function __construct($name='', $isFocus=0)
        {
            $this->name = $name;
            $this->isFocus = $isFocus;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::Navigation';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_common__t_Navigation;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_common__t_Navigation);
        }

        public $name;
        public $isFocus;
    }

    class com_jpgk_catering_rpc_common_NavigationPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::common::Navigation', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::common::Navigation', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::Navigation';
        }
    }

    $com_jpgk_catering_rpc_common__t_Navigation = IcePHP_defineClass('::com::jpgk::catering::rpc::common::Navigation', 'com_jpgk_catering_rpc_common_Navigation', -1, false, false, $Ice__t_Object, null, array(
        array('name', $IcePHP__t_string, false, 0),
        array('isFocus', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_common__t_NavigationPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_common__t_Navigation);
}

global $com_jpgk_catering_rpc_common__t_NavigationSeq;

if(!isset($com_jpgk_catering_rpc_common__t_NavigationSeq))
{
    $com_jpgk_catering_rpc_common__t_NavigationSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::common::NavigationSeq', $com_jpgk_catering_rpc_common__t_Navigation);
}

global $com_jpgk_catering_rpc_common__t_DeliveryAddress;
global $com_jpgk_catering_rpc_common__t_DeliveryAddressPrx;

if(!class_exists('com_jpgk_catering_rpc_common_DeliveryAddress'))
{
    class com_jpgk_catering_rpc_common_DeliveryAddress extends Ice_ObjectImpl
    {
        public function __construct($id=0, $detailAddress='', $provinceId=0, $cityId=0, $province='', $city='', $isDefault=0, $uid=0, $userName='', $phone='')
        {
            $this->id = $id;
            $this->detailAddress = $detailAddress;
            $this->provinceId = $provinceId;
            $this->cityId = $cityId;
            $this->province = $province;
            $this->city = $city;
            $this->isDefault = $isDefault;
            $this->uid = $uid;
            $this->userName = $userName;
            $this->phone = $phone;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::DeliveryAddress';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_common__t_DeliveryAddress;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_common__t_DeliveryAddress);
        }

        public $id;
        public $detailAddress;
        public $provinceId;
        public $cityId;
        public $province;
        public $city;
        public $isDefault;
        public $uid;
        public $userName;
        public $phone;
    }

    class com_jpgk_catering_rpc_common_DeliveryAddressPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::common::DeliveryAddress', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::common::DeliveryAddress', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::common::DeliveryAddress';
        }
    }

    $com_jpgk_catering_rpc_common__t_DeliveryAddress = IcePHP_defineClass('::com::jpgk::catering::rpc::common::DeliveryAddress', 'com_jpgk_catering_rpc_common_DeliveryAddress', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('detailAddress', $IcePHP__t_string, false, 0),
        array('provinceId', $IcePHP__t_int, false, 0),
        array('cityId', $IcePHP__t_int, false, 0),
        array('province', $IcePHP__t_string, false, 0),
        array('city', $IcePHP__t_string, false, 0),
        array('isDefault', $IcePHP__t_int, false, 0),
        array('uid', $IcePHP__t_int, false, 0),
        array('userName', $IcePHP__t_string, false, 0),
        array('phone', $IcePHP__t_string, false, 0)));

    $com_jpgk_catering_rpc_common__t_DeliveryAddressPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_common__t_DeliveryAddress);
}

global $com_jpgk_catering_rpc_common__t_DeliveryAddressSeq;

if(!isset($com_jpgk_catering_rpc_common__t_DeliveryAddressSeq))
{
    $com_jpgk_catering_rpc_common__t_DeliveryAddressSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::common::DeliveryAddressSeq', $com_jpgk_catering_rpc_common__t_DeliveryAddress);
}
?>
