<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `UCenter.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once "Ice.php";
require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';
require_once APP_PATH.'Common/Lib/Ice/FileSystem.php';
require_once APP_PATH.'Common/Lib/Ice/ResponseModel.php';
require_once APP_PATH.'Common/Lib/Ice/clientphp/model/UCenterClass.php';

global $com_jpgk_catering_rpc_ucenter__t_V0316Userinfo;
global $com_jpgk_catering_rpc_ucenter__t_V0316UserinfoPrx;

if(!class_exists('com_jpgk_catering_rpc_ucenter_V0316Userinfo'))
{
    class com_jpgk_catering_rpc_ucenter_V0316Userinfo extends com_jpgk_catering_rpc_ucenter_UserinfoModel
    {
        public function __construct($uid=0, $username='', $nickname='', $score1=0, $avatar='', $level='', $signature='', $ans=0, $following=0, $sex=0, $posProvince=0, $posCity=0, $posDistrict=0, $birthday='', $brand='', $department='', $position='', $job='', $phone='', $company='', $jobName='', $jobId=0)
        {
            parent::__construct($uid, $username, $nickname, $score1, $avatar, $level, $signature, $ans, $following, $sex, $posProvince, $posCity, $posDistrict, $birthday, $brand, $department, $position, $job, $phone, $company);
            $this->jobName = $jobName;
            $this->jobId = $jobId;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::ucenter::V0316Userinfo';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_ucenter__t_V0316Userinfo;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_ucenter__t_V0316Userinfo);
        }

        public $jobName;
        public $jobId;
    }

    class com_jpgk_catering_rpc_ucenter_V0316UserinfoPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::ucenter::V0316Userinfo', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::ucenter::V0316Userinfo', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::ucenter::V0316Userinfo';
        }
    }

    $com_jpgk_catering_rpc_ucenter__t_V0316Userinfo = IcePHP_defineClass('::com::jpgk::catering::rpc::ucenter::V0316Userinfo', 'com_jpgk_catering_rpc_ucenter_V0316Userinfo', -1, false, false, $com_jpgk_catering_rpc_ucenter__t_UserinfoModel, null, array(
        array('jobName', $IcePHP__t_string, false, 0),
        array('jobId', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_ucenter__t_V0316UserinfoPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_ucenter__t_V0316Userinfo);
}

global $com_jpgk_catering_rpc_ucenter__t_V0324Userinfo;
global $com_jpgk_catering_rpc_ucenter__t_V0324UserinfoPrx;

if(!class_exists('com_jpgk_catering_rpc_ucenter_V0324Userinfo'))
{
    class com_jpgk_catering_rpc_ucenter_V0324Userinfo extends com_jpgk_catering_rpc_ucenter_V0316Userinfo
    {
        public function __construct($uid=0, $username='', $nickname='', $score1=0, $avatar='', $level='', $signature='', $ans=0, $following=0, $sex=0, $posProvince=0, $posCity=0, $posDistrict=0, $birthday='', $brand='', $department='', $position='', $job='', $phone='', $company='', $jobName='', $jobId=0, $isHonor=0)
        {
            parent::__construct($uid, $username, $nickname, $score1, $avatar, $level, $signature, $ans, $following, $sex, $posProvince, $posCity, $posDistrict, $birthday, $brand, $department, $position, $job, $phone, $company, $jobName, $jobId);
            $this->isHonor = $isHonor;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::ucenter::V0324Userinfo';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_ucenter__t_V0324Userinfo;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_ucenter__t_V0324Userinfo);
        }

        public $isHonor;
    }

    class com_jpgk_catering_rpc_ucenter_V0324UserinfoPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::ucenter::V0324Userinfo', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::ucenter::V0324Userinfo', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::ucenter::V0324Userinfo';
        }
    }

    $com_jpgk_catering_rpc_ucenter__t_V0324Userinfo = IcePHP_defineClass('::com::jpgk::catering::rpc::ucenter::V0324Userinfo', 'com_jpgk_catering_rpc_ucenter_V0324Userinfo', -1, false, false, $com_jpgk_catering_rpc_ucenter__t_V0316Userinfo, null, array(
        array('isHonor', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_ucenter__t_V0324UserinfoPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_ucenter__t_V0324Userinfo);
}

global $com_jpgk_catering_rpc_ucenter__t_UCenterService;
global $com_jpgk_catering_rpc_ucenter__t_UCenterServicePrx;

if(!interface_exists('com_jpgk_catering_rpc_ucenter_UCenterService'))
{
    interface com_jpgk_catering_rpc_ucenter_UCenterService extends com_jpgk_common_rpc_BaseService
    {
        public function updateBrand($uid, $brand);
        public function getUserInfoV0324($uId);
        public function getUserInfoV0316($uId);
        public function updateUserJob($uId, $jobId);
        public function updateUserInfoV0316($uId, $jobId, $brand);
        public function register($username, $pwd, $verify);
        public function verifyCheck($username, $verify);
        public function registerWithCity($userRegistModel);
        public function appOpen($uid);
        public function regVerify($username);
        public function regVerifyV0425($username);
        public function userinfo($uid);
        public function checking($username);
        public function uploadAvatar($user, $model);
        public function updateUserinfo($auth, $userinfo);
        public function updatePassword($username, $pwd, $verify);
    }

    class com_jpgk_catering_rpc_ucenter_UCenterServicePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::ucenter::UCenterService', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::ucenter::UCenterService', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::ucenter::UCenterService';
        }
    }

    $com_jpgk_catering_rpc_ucenter__t_UCenterService = IcePHP_defineClass('::com::jpgk::catering::rpc::ucenter::UCenterService', 'com_jpgk_catering_rpc_ucenter_UCenterService', -1, true, false, $Ice__t_Object, array($com_jpgk_common_rpc__t_BaseService), null);

    $com_jpgk_catering_rpc_ucenter__t_UCenterServicePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_ucenter__t_UCenterService);

    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'updateBrand', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_string, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'getUserInfoV0324', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_ucenter__t_V0324Userinfo, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'getUserInfoV0316', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_ucenter__t_V0316Userinfo, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'updateUserJob', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'updateUserInfoV0316', 0, 0, 0, array(array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_string, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'register', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_bool, false, 0), array($com_jpgk_common_rpc__t_BaseException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'verifyCheck', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'registerWithCity', 0, 0, 0, array(array($com_jpgk_catering_rpc_ucenter__t_UserRegistModel, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'appOpen', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'regVerify', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_string, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'regVerifyV0425', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_string, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'userinfo', 0, 0, 0, array(array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_ucenter__t_UserinfoModel, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'checking', 0, 0, 0, array(array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_bool, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'uploadAvatar', 0, 0, 0, array(array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_FileSystem_rpc__t_UploadModel, false, 0)), null, array($IcePHP__t_string, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'updateUserinfo', 0, 0, 0, array(array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_catering_rpc_ucenter__t_UserinfoModel, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UCenterService, 'updatePassword', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($com_jpgk_common_rpc__t_ResponseModel, false, 0), null);
}

global $com_jpgk_catering_rpc_ucenter__t_UAuthService;
global $com_jpgk_catering_rpc_ucenter__t_UAuthServicePrx;

if(!interface_exists('com_jpgk_catering_rpc_ucenter_UAuthService'))
{
    interface com_jpgk_catering_rpc_ucenter_UAuthService extends com_jpgk_common_rpc_BaseService
    {
        public function authorizationWithSource($username, $verify, $source);
        public function authorizationWithSourceAndCode($username, $verify, $source, $statisticsId, $appCode);
        public function authorizationWithSourceAndStatisticsId($username, $verify, $source, $statisticsId);
        public function authorization($username, $verify);
        public function authorizationByPwd($username, $pwd);
        public function logout($user);
        public function checkLogin($username, $token);
    }

    class com_jpgk_catering_rpc_ucenter_UAuthServicePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::ucenter::UAuthService', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::ucenter::UAuthService', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::ucenter::UAuthService';
        }
    }

    $com_jpgk_catering_rpc_ucenter__t_UAuthService = IcePHP_defineClass('::com::jpgk::catering::rpc::ucenter::UAuthService', 'com_jpgk_catering_rpc_ucenter_UAuthService', -1, true, false, $Ice__t_Object, array($com_jpgk_common_rpc__t_BaseService), null);

    $com_jpgk_catering_rpc_ucenter__t_UAuthServicePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_ucenter__t_UAuthService);

    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UAuthService, 'authorizationWithSource', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UAuthService, 'authorizationWithSourceAndCode', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_string, false, 0)), null, array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UAuthService, 'authorizationWithSourceAndStatisticsId', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0), array($IcePHP__t_int, false, 0), array($IcePHP__t_int, false, 0)), null, array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UAuthService, 'authorization', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UAuthService, 'authorizationByPwd', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UAuthService, 'logout', 0, 0, 0, array(array($com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0)), null, array($IcePHP__t_bool, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
    IcePHP_defineOperation($com_jpgk_catering_rpc_ucenter__t_UAuthService, 'checkLogin', 0, 0, 0, array(array($IcePHP__t_string, false, 0), array($IcePHP__t_string, false, 0)), null, array($IcePHP__t_bool, false, 0), array($com_jpgk_common_rpc__t_NullValueException));
}
?>
