<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `CommentClass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/clientphp/model/UCenter.php';

global $com_jpgk_catering_rpc_comment__t_CommentException;

if(!class_exists('com_jpgk_catering_rpc_comment_CommentException'))
{
    class com_jpgk_catering_rpc_comment_CommentException extends com_jpgk_common_rpc_BaseException
    {
        public function __construct($reason='', $userMessage='')
        {
            parent::__construct($reason, $userMessage);
        }

        public function ice_name()
        {
            return 'com::jpgk::catering::rpc::comment::CommentException';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_comment__t_CommentException;
            return IcePHP_stringifyException($this, $com_jpgk_catering_rpc_comment__t_CommentException);
        }
    }

    $com_jpgk_catering_rpc_comment__t_CommentException = IcePHP_defineException('::com::jpgk::catering::rpc::comment::CommentException', 'com_jpgk_catering_rpc_comment_CommentException', false, $com_jpgk_common_rpc__t_BaseException, null);
}

global $com_jpgk_catering_rpc_comment__t_CommentApp;

if(!class_exists('com_jpgk_catering_rpc_comment_CommentApp'))
{
    class com_jpgk_catering_rpc_comment_CommentApp
    {
        const News = 0;
        const Event = 1;
        const Post = 2;
        const Resource = 3;
        const SHM = 4;
        const SupplyMarket = 5;
        const CircleVideo = 6;
    }

    $com_jpgk_catering_rpc_comment__t_CommentApp = IcePHP_defineEnum('::com::jpgk::catering::rpc::comment::CommentApp', array('News', 0, 'Event', 1, 'Post', 2, 'Resource', 3, 'SHM', 4, 'SupplyMarket', 5, 'CircleVideo', 6));
}

global $com_jpgk_catering_rpc_comment__t_CommentSaveModel;
global $com_jpgk_catering_rpc_comment__t_CommentSaveModelPrx;

if(!class_exists('com_jpgk_catering_rpc_comment_CommentSaveModel'))
{
    class com_jpgk_catering_rpc_comment_CommentSaveModel extends Ice_ObjectImpl
    {
        public function __construct($rowId=0, $content='', $area='', $app=com_jpgk_catering_rpc_comment_CommentApp::News, $user=null, $pid=0)
        {
            $this->rowId = $rowId;
            $this->content = $content;
            $this->area = $area;
            $this->app = $app;
            $this->user = $user;
            $this->pid = $pid;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::CommentSaveModel';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_comment__t_CommentSaveModel;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_comment__t_CommentSaveModel);
        }

        public $rowId;
        public $content;
        public $area;
        public $app;
        public $user;
        public $pid;
    }

    class com_jpgk_catering_rpc_comment_CommentSaveModelPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::comment::CommentSaveModel', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::comment::CommentSaveModel', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::CommentSaveModel';
        }
    }

    $com_jpgk_catering_rpc_comment__t_CommentSaveModel = IcePHP_declareClass('::com::jpgk::catering::rpc::comment::CommentSaveModel');
    $com_jpgk_catering_rpc_comment__t_CommentSaveModelPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::comment::CommentSaveModel');

    $com_jpgk_catering_rpc_comment__t_CommentSaveModel = IcePHP_defineClass('::com::jpgk::catering::rpc::comment::CommentSaveModel', 'com_jpgk_catering_rpc_comment_CommentSaveModel', -1, false, false, $Ice__t_Object, null, array(
        array('rowId', $IcePHP__t_int, false, 0),
        array('content', $IcePHP__t_string, false, 0),
        array('area', $IcePHP__t_string, false, 0),
        array('app', $com_jpgk_catering_rpc_comment__t_CommentApp, false, 0),
        array('user', $com_jpgk_catering_rpc_ucenter__t_UCenterModel, false, 0),
        array('pid', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_comment__t_CommentSaveModelPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_comment__t_CommentSaveModel);
}

global $com_jpgk_catering_rpc_comment__t_CommentReplyModel;
global $com_jpgk_catering_rpc_comment__t_CommentReplyModelPrx;

if(!class_exists('com_jpgk_catering_rpc_comment_CommentReplyModel'))
{
    class com_jpgk_catering_rpc_comment_CommentReplyModel extends Ice_ObjectImpl
    {
        public function __construct($id=0, $app=com_jpgk_catering_rpc_comment_CommentApp::News, $mod='', $rowId=0, $content='', $createTime=0, $status=0, $area='', $title='', $uid=0, $support=false, $supportNum=0, $pid=0)
        {
            $this->id = $id;
            $this->app = $app;
            $this->mod = $mod;
            $this->rowId = $rowId;
            $this->content = $content;
            $this->createTime = $createTime;
            $this->status = $status;
            $this->area = $area;
            $this->title = $title;
            $this->uid = $uid;
            $this->support = $support;
            $this->supportNum = $supportNum;
            $this->pid = $pid;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::CommentReplyModel';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_comment__t_CommentReplyModel;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_comment__t_CommentReplyModel);
        }

        public $id;
        public $app;
        public $mod;
        public $rowId;
        public $content;
        public $createTime;
        public $status;
        public $area;
        public $title;
        public $uid;
        public $support;
        public $supportNum;
        public $pid;
    }

    class com_jpgk_catering_rpc_comment_CommentReplyModelPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::comment::CommentReplyModel', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::comment::CommentReplyModel', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::CommentReplyModel';
        }
    }

    $com_jpgk_catering_rpc_comment__t_CommentReplyModel = IcePHP_defineClass('::com::jpgk::catering::rpc::comment::CommentReplyModel', 'com_jpgk_catering_rpc_comment_CommentReplyModel', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('app', $com_jpgk_catering_rpc_comment__t_CommentApp, false, 0),
        array('mod', $IcePHP__t_string, false, 0),
        array('rowId', $IcePHP__t_int, false, 0),
        array('content', $IcePHP__t_string, false, 0),
        array('createTime', $IcePHP__t_int, false, 0),
        array('status', $IcePHP__t_int, false, 0),
        array('area', $IcePHP__t_string, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('uid', $IcePHP__t_int, false, 0),
        array('support', $IcePHP__t_bool, false, 0),
        array('supportNum', $IcePHP__t_int, false, 0),
        array('pid', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_comment__t_CommentReplyModelPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_comment__t_CommentReplyModel);
}

global $com_jpgk_catering_rpc_comment__t_CommentReplySeq;

if(!isset($com_jpgk_catering_rpc_comment__t_CommentReplySeq))
{
    $com_jpgk_catering_rpc_comment__t_CommentReplySeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::comment::CommentReplySeq', $com_jpgk_catering_rpc_comment__t_CommentReplyModel);
}

global $com_jpgk_catering_rpc_comment__t_CommentModel;
global $com_jpgk_catering_rpc_comment__t_CommentModelPrx;

if(!class_exists('com_jpgk_catering_rpc_comment_CommentModel'))
{
    class com_jpgk_catering_rpc_comment_CommentModel extends Ice_ObjectImpl
    {
        public function __construct($id=0, $uid=0, $app=com_jpgk_catering_rpc_comment_CommentApp::News, $mod='', $rowId=0, $content='', $createTime=0, $status=0, $area='', $title='', $user=null, $support=false, $supportNum=0, $pid=0, $commentReplys=null)
        {
            $this->id = $id;
            $this->uid = $uid;
            $this->app = $app;
            $this->mod = $mod;
            $this->rowId = $rowId;
            $this->content = $content;
            $this->createTime = $createTime;
            $this->status = $status;
            $this->area = $area;
            $this->title = $title;
            $this->user = $user;
            $this->support = $support;
            $this->supportNum = $supportNum;
            $this->pid = $pid;
            $this->commentReplys = $commentReplys;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::CommentModel';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_comment__t_CommentModel;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_comment__t_CommentModel);
        }

        public $id;
        public $uid;
        public $app;
        public $mod;
        public $rowId;
        public $content;
        public $createTime;
        public $status;
        public $area;
        public $title;
        public $user;
        public $support;
        public $supportNum;
        public $pid;
        public $commentReplys;
    }

    class com_jpgk_catering_rpc_comment_CommentModelPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::comment::CommentModel', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::comment::CommentModel', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::comment::CommentModel';
        }
    }

    $com_jpgk_catering_rpc_comment__t_CommentModel = IcePHP_declareClass('::com::jpgk::catering::rpc::comment::CommentModel');
    $com_jpgk_catering_rpc_comment__t_CommentModelPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::comment::CommentModel');

    $com_jpgk_catering_rpc_comment__t_CommentModel = IcePHP_defineClass('::com::jpgk::catering::rpc::comment::CommentModel', 'com_jpgk_catering_rpc_comment_CommentModel', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('uid', $IcePHP__t_int, false, 0),
        array('app', $com_jpgk_catering_rpc_comment__t_CommentApp, false, 0),
        array('mod', $IcePHP__t_string, false, 0),
        array('rowId', $IcePHP__t_int, false, 0),
        array('content', $IcePHP__t_string, false, 0),
        array('createTime', $IcePHP__t_int, false, 0),
        array('status', $IcePHP__t_int, false, 0),
        array('area', $IcePHP__t_string, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('user', $com_jpgk_catering_rpc_ucenter__t_UserinfoModel, false, 0),
        array('support', $IcePHP__t_bool, false, 0),
        array('supportNum', $IcePHP__t_int, false, 0),
        array('pid', $IcePHP__t_int, false, 0),
        array('commentReplys', $com_jpgk_catering_rpc_comment__t_CommentReplySeq, false, 0)));

    $com_jpgk_catering_rpc_comment__t_CommentModelPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_comment__t_CommentModel);
}

global $com_jpgk_catering_rpc_comment__t_CommentSeq;

if(!isset($com_jpgk_catering_rpc_comment__t_CommentSeq))
{
    $com_jpgk_catering_rpc_comment__t_CommentSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::comment::CommentSeq', $com_jpgk_catering_rpc_comment__t_CommentModel);
}
?>
