<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `FileSystem.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//
require_once "Ice.php";

require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';

global $com_jpgk_FileSystem_rpc__t_UploadException;

if(!class_exists('com_jpgk_FileSystem_rpc_UploadException'))
{
    class com_jpgk_FileSystem_rpc_UploadException extends com_jpgk_common_rpc_BaseException
    {
        public function __construct($reason='', $userMessage='')
        {
            parent::__construct($reason, $userMessage);
        }

        public function ice_name()
        {
            return 'com::jpgk::FileSystem::rpc::UploadException';
        }

        public function __toString()
        {
            global $com_jpgk_FileSystem_rpc__t_UploadException;
            return IcePHP_stringifyException($this, $com_jpgk_FileSystem_rpc__t_UploadException);
        }
    }

    $com_jpgk_FileSystem_rpc__t_UploadException = IcePHP_defineException('::com::jpgk::FileSystem::rpc::UploadException', 'com_jpgk_FileSystem_rpc_UploadException', false, $com_jpgk_common_rpc__t_BaseException, null);
}

global $com_jpgk_FileSystem_rpc__t_FileBuffer;

if(!isset($com_jpgk_FileSystem_rpc__t_FileBuffer))
{
    $com_jpgk_FileSystem_rpc__t_FileBuffer = IcePHP_defineSequence('::com::jpgk::FileSystem::rpc::FileBuffer', $IcePHP__t_byte);
}

global $com_jpgk_FileSystem_rpc__t_UploadModel;

if(!class_exists('com_jpgk_FileSystem_rpc_UploadModel'))
{
    class com_jpgk_FileSystem_rpc_UploadModel
    {
        public function __construct($extension='', $buffer=null)
        {
            $this->extension = $extension;
            $this->buffer = $buffer;
        }

        public function __toString()
        {
            global $com_jpgk_FileSystem_rpc__t_UploadModel;
            return IcePHP_stringify($this, $com_jpgk_FileSystem_rpc__t_UploadModel);
        }

        public $extension;
        public $buffer;
    }

    $com_jpgk_FileSystem_rpc__t_UploadModel = IcePHP_defineStruct('::com::jpgk::FileSystem::rpc::UploadModel', 'com_jpgk_FileSystem_rpc_UploadModel', array(
        array('extension', $IcePHP__t_string), 
        array('buffer', $com_jpgk_FileSystem_rpc__t_FileBuffer)));
}

global $com_jpgk_FileSystem_rpc__t_UploadSeq;

if(!isset($com_jpgk_FileSystem_rpc__t_UploadSeq))
{
    $com_jpgk_FileSystem_rpc__t_UploadSeq = IcePHP_defineSequence('::com::jpgk::FileSystem::rpc::UploadSeq', $com_jpgk_FileSystem_rpc__t_UploadModel);
}

global $com_jpgk_FileSystem_rpc__t_FileModel;

if(!class_exists('com_jpgk_FileSystem_rpc_FileModel'))
{
    class com_jpgk_FileSystem_rpc_FileModel
    {
        public function __construct($fileId=0, $localPath='', $urlPath='')
        {
            $this->fileId = $fileId;
            $this->localPath = $localPath;
            $this->urlPath = $urlPath;
        }

        public function __toString()
        {
            global $com_jpgk_FileSystem_rpc__t_FileModel;
            return IcePHP_stringify($this, $com_jpgk_FileSystem_rpc__t_FileModel);
        }

        public $fileId;
        public $localPath;
        public $urlPath;
    }

    $com_jpgk_FileSystem_rpc__t_FileModel = IcePHP_defineStruct('::com::jpgk::FileSystem::rpc::FileModel', 'com_jpgk_FileSystem_rpc_FileModel', array(
        array('fileId', $IcePHP__t_int), 
        array('localPath', $IcePHP__t_string), 
        array('urlPath', $IcePHP__t_string)));
}
global $com_jpgk_FileSystem_rpc__t_FileSeq;


if(!isset($com_jpgk_FileSystem_rpc__t_FileSeq))
{
    $com_jpgk_FileSystem_rpc__t_FileSeq = IcePHP_defineSequence('::com::jpgk::FileSystem::rpc::FileSeq', $com_jpgk_FileSystem_rpc__t_FileModel);
}
?>
