<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `SupplyMarketingClass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';
require_once APP_PATH.'Common/Lib/Ice/Page.php';
require_once APP_PATH.'Common/Lib/Ice/common.php';

global $com_jpgk_catering_rpc_supplymarketing__t_ProductCategory;
global $com_jpgk_catering_rpc_supplymarketing__t_ProductCategoryPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_ProductCategory'))
{
    class com_jpgk_catering_rpc_supplymarketing_ProductCategory extends Ice_ObjectImpl
    {
        public function __construct($id=0, $name='', $pid=0, $iconUrl='', $hotIconUrl='', $hotDegree=0)
        {
            $this->id = $id;
            $this->name = $name;
            $this->pid = $pid;
            $this->iconUrl = $iconUrl;
            $this->hotIconUrl = $hotIconUrl;
            $this->hotDegree = $hotDegree;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::ProductCategory';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_ProductCategory;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_ProductCategory);
        }

        public $id;
        public $name;
        public $pid;
        public $iconUrl;
        public $hotIconUrl;
        public $hotDegree;
    }

    class com_jpgk_catering_rpc_supplymarketing_ProductCategoryPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::ProductCategory', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::ProductCategory', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::ProductCategory';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_ProductCategory = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::ProductCategory', 'com_jpgk_catering_rpc_supplymarketing_ProductCategory', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('name', $IcePHP__t_string, false, 0),
        array('pid', $IcePHP__t_int, false, 0),
        array('iconUrl', $IcePHP__t_string, false, 0),
        array('hotIconUrl', $IcePHP__t_string, false, 0),
        array('hotDegree', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_ProductCategoryPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_ProductCategory);
}

global $com_jpgk_catering_rpc_supplymarketing__t_ProductCategorySeq;

if(!isset($com_jpgk_catering_rpc_supplymarketing__t_ProductCategorySeq))
{
    $com_jpgk_catering_rpc_supplymarketing__t_ProductCategorySeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::supplymarketing::ProductCategorySeq', $com_jpgk_catering_rpc_supplymarketing__t_ProductCategory);
}

global $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategory;
global $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategoryPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_TopProductCategory'))
{
    class com_jpgk_catering_rpc_supplymarketing_TopProductCategory extends Ice_ObjectImpl
    {
        public function __construct($id=0, $name='', $iconUrl='', $productCategorys=null)
        {
            $this->id = $id;
            $this->name = $name;
            $this->iconUrl = $iconUrl;
            $this->productCategorys = $productCategorys;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::TopProductCategory';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategory;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategory);
        }

        public $id;
        public $name;
        public $iconUrl;
        public $productCategorys;
    }

    class com_jpgk_catering_rpc_supplymarketing_TopProductCategoryPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::TopProductCategory', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::TopProductCategory', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::TopProductCategory';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategory = IcePHP_declareClass('::com::jpgk::catering::rpc::supplymarketing::TopProductCategory');
    $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategoryPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::supplymarketing::TopProductCategory');

    $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategory = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::TopProductCategory', 'com_jpgk_catering_rpc_supplymarketing_TopProductCategory', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('name', $IcePHP__t_string, false, 0),
        array('iconUrl', $IcePHP__t_string, false, 0),
        array('productCategorys', $com_jpgk_catering_rpc_supplymarketing__t_ProductCategorySeq, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategoryPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_TopProductCategory);
}

global $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategorySeq;

if(!isset($com_jpgk_catering_rpc_supplymarketing__t_TopProductCategorySeq))
{
    $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategorySeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::supplymarketing::TopProductCategorySeq', $com_jpgk_catering_rpc_supplymarketing__t_TopProductCategory);
}

global $com_jpgk_catering_rpc_supplymarketing__t_SuccessCase;
global $com_jpgk_catering_rpc_supplymarketing__t_SuccessCasePrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_SuccessCase'))
{
    class com_jpgk_catering_rpc_supplymarketing_SuccessCase extends Ice_ObjectImpl
    {
        public function __construct($id=0, $imageUrl='')
        {
            $this->id = $id;
            $this->imageUrl = $imageUrl;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::SuccessCase';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_SuccessCase;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_SuccessCase);
        }

        public $id;
        public $imageUrl;
    }

    class com_jpgk_catering_rpc_supplymarketing_SuccessCasePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::SuccessCase', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::SuccessCase', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::SuccessCase';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_SuccessCase = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::SuccessCase', 'com_jpgk_catering_rpc_supplymarketing_SuccessCase', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('imageUrl', $IcePHP__t_string, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_SuccessCasePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_SuccessCase);
}

global $com_jpgk_catering_rpc_supplymarketing__t_SuccessCaseSeq;

if(!isset($com_jpgk_catering_rpc_supplymarketing__t_SuccessCaseSeq))
{
    $com_jpgk_catering_rpc_supplymarketing__t_SuccessCaseSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::supplymarketing::SuccessCaseSeq', $com_jpgk_catering_rpc_supplymarketing__t_SuccessCase);
}

global $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualification;
global $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualificationPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_CompanyQualification'))
{
    class com_jpgk_catering_rpc_supplymarketing_CompanyQualification extends Ice_ObjectImpl
    {
        public function __construct($id=0, $imageUrl='')
        {
            $this->id = $id;
            $this->imageUrl = $imageUrl;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::CompanyQualification';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualification;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualification);
        }

        public $id;
        public $imageUrl;
    }

    class com_jpgk_catering_rpc_supplymarketing_CompanyQualificationPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::CompanyQualification', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::CompanyQualification', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::CompanyQualification';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualification = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::CompanyQualification', 'com_jpgk_catering_rpc_supplymarketing_CompanyQualification', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('imageUrl', $IcePHP__t_string, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualificationPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_CompanyQualification);
}

global $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualificationSeq;

if(!isset($com_jpgk_catering_rpc_supplymarketing__t_CompanyQualificationSeq))
{
    $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualificationSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::supplymarketing::CompanyQualificationSeq', $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualification);
}

global $com_jpgk_catering_rpc_supplymarketing__t_Company;
global $com_jpgk_catering_rpc_supplymarketing__t_CompanyPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_Company'))
{
    class com_jpgk_catering_rpc_supplymarketing_Company extends Ice_ObjectImpl
    {
        public function __construct($id=0, $name='', $description='', $phone='', $address='', $logoUrl='', $longitude=0, $latitude=0, $lisenseStatus=0, $regTime=0, $successCases=null, $companyQualifications=null)
        {
            $this->id = $id;
            $this->name = $name;
            $this->description = $description;
            $this->phone = $phone;
            $this->address = $address;
            $this->logoUrl = $logoUrl;
            $this->longitude = $longitude;
            $this->latitude = $latitude;
            $this->lisenseStatus = $lisenseStatus;
            $this->regTime = $regTime;
            $this->successCases = $successCases;
            $this->companyQualifications = $companyQualifications;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::Company';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_Company;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_Company);
        }

        public $id;
        public $name;
        public $description;
        public $phone;
        public $address;
        public $logoUrl;
        public $longitude;
        public $latitude;
        public $lisenseStatus;
        public $regTime;
        public $successCases;
        public $companyQualifications;
    }

    class com_jpgk_catering_rpc_supplymarketing_CompanyPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::Company', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::Company', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::Company';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_Company = IcePHP_declareClass('::com::jpgk::catering::rpc::supplymarketing::Company');
    $com_jpgk_catering_rpc_supplymarketing__t_CompanyPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::supplymarketing::Company');

    $com_jpgk_catering_rpc_supplymarketing__t_Company = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::Company', 'com_jpgk_catering_rpc_supplymarketing_Company', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('name', $IcePHP__t_string, false, 0),
        array('description', $IcePHP__t_string, false, 0),
        array('phone', $IcePHP__t_string, false, 0),
        array('address', $IcePHP__t_string, false, 0),
        array('logoUrl', $IcePHP__t_string, false, 0),
        array('longitude', $IcePHP__t_int, false, 0),
        array('latitude', $IcePHP__t_int, false, 0),
        array('lisenseStatus', $IcePHP__t_int, false, 0),
        array('regTime', $IcePHP__t_int, false, 0),
        array('successCases', $com_jpgk_catering_rpc_supplymarketing__t_SuccessCaseSeq, false, 0),
        array('companyQualifications', $com_jpgk_catering_rpc_supplymarketing__t_CompanyQualificationSeq, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_CompanyPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_Company);
}

global $com_jpgk_catering_rpc_supplymarketing__t_Product;
global $com_jpgk_catering_rpc_supplymarketing__t_ProductPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_Product'))
{
    class com_jpgk_catering_rpc_supplymarketing_Product extends Ice_ObjectImpl
    {
        public function __construct($id=0, $title='', $description='', $price=0.0, $priceUnit='', $categoryText='', $oneLevelCateg=null, $twoLevelCateg=null, $threeLevelCateg=null, $districtText='', $views=0, $collectionUserNum=0, $consultNum=0, $isCollected=0, $isAppointed=0, $pictures=null, $successCases=null, $company=null)
        {
            $this->id = $id;
            $this->title = $title;
            $this->description = $description;
            $this->price = $price;
            $this->priceUnit = $priceUnit;
            $this->categoryText = $categoryText;
            $this->oneLevelCateg = $oneLevelCateg;
            $this->twoLevelCateg = $twoLevelCateg;
            $this->threeLevelCateg = $threeLevelCateg;
            $this->districtText = $districtText;
            $this->views = $views;
            $this->collectionUserNum = $collectionUserNum;
            $this->consultNum = $consultNum;
            $this->isCollected = $isCollected;
            $this->isAppointed = $isAppointed;
            $this->pictures = $pictures;
            $this->successCases = $successCases;
            $this->company = $company;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::Product';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_Product;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_Product);
        }

        public $id;
        public $title;
        public $description;
        public $price;
        public $priceUnit;
        public $categoryText;
        public $oneLevelCateg;
        public $twoLevelCateg;
        public $threeLevelCateg;
        public $districtText;
        public $views;
        public $collectionUserNum;
        public $consultNum;
        public $isCollected;
        public $isAppointed;
        public $pictures;
        public $successCases;
        public $company;
    }

    class com_jpgk_catering_rpc_supplymarketing_ProductPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::Product', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::Product', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::Product';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_Product = IcePHP_declareClass('::com::jpgk::catering::rpc::supplymarketing::Product');
    $com_jpgk_catering_rpc_supplymarketing__t_ProductPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::supplymarketing::Product');

    $com_jpgk_catering_rpc_supplymarketing__t_Product = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::Product', 'com_jpgk_catering_rpc_supplymarketing_Product', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('description', $IcePHP__t_string, false, 0),
        array('price', $IcePHP__t_double, false, 0),
        array('priceUnit', $IcePHP__t_string, false, 0),
        array('categoryText', $IcePHP__t_string, false, 0),
        array('oneLevelCateg', $com_jpgk_catering_rpc_supplymarketing__t_ProductCategory, false, 0),
        array('twoLevelCateg', $com_jpgk_catering_rpc_supplymarketing__t_ProductCategory, false, 0),
        array('threeLevelCateg', $com_jpgk_catering_rpc_supplymarketing__t_ProductCategory, false, 0),
        array('districtText', $IcePHP__t_string, false, 0),
        array('views', $IcePHP__t_int, false, 0),
        array('collectionUserNum', $IcePHP__t_int, false, 0),
        array('consultNum', $IcePHP__t_int, false, 0),
        array('isCollected', $IcePHP__t_int, false, 0),
        array('isAppointed', $IcePHP__t_int, false, 0),
        array('pictures', $com_jpgk_catering_rpc_common__t_PictureSeq, false, 0),
        array('successCases', $com_jpgk_catering_rpc_supplymarketing__t_SuccessCaseSeq, false, 0),
        array('company', $com_jpgk_catering_rpc_supplymarketing__t_Company, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_ProductPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_Product);
}

global $com_jpgk_catering_rpc_supplymarketing__t_ProductSeq;

if(!isset($com_jpgk_catering_rpc_supplymarketing__t_ProductSeq))
{
    $com_jpgk_catering_rpc_supplymarketing__t_ProductSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::supplymarketing::ProductSeq', $com_jpgk_catering_rpc_supplymarketing__t_Product);
}

global $com_jpgk_catering_rpc_supplymarketing__t_ProductSort;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_ProductSort'))
{
    class com_jpgk_catering_rpc_supplymarketing_ProductSort
    {
        const Integrated = 0;
        const Newest = 1;
        const HighestPrice = 2;
        const LowestPrice = 3;
    }

    $com_jpgk_catering_rpc_supplymarketing__t_ProductSort = IcePHP_defineEnum('::com::jpgk::catering::rpc::supplymarketing::ProductSort', array('Integrated', 0, 'Newest', 1, 'HighestPrice', 2, 'LowestPrice', 3));
}

global $com_jpgk_catering_rpc_supplymarketing__t_Appointment;
global $com_jpgk_catering_rpc_supplymarketing__t_AppointmentPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_Appointment'))
{
    class com_jpgk_catering_rpc_supplymarketing_Appointment extends Ice_ObjectImpl
    {
        public function __construct($id=0, $name='', $appointmentTime=0, $phone='', $productId=0, $uid=0, $status=0, $remark='', $verificationCode='', $product=null)
        {
            $this->id = $id;
            $this->name = $name;
            $this->appointmentTime = $appointmentTime;
            $this->phone = $phone;
            $this->productId = $productId;
            $this->uid = $uid;
            $this->status = $status;
            $this->remark = $remark;
            $this->verificationCode = $verificationCode;
            $this->product = $product;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::Appointment';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_Appointment;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_Appointment);
        }

        public $id;
        public $name;
        public $appointmentTime;
        public $phone;
        public $productId;
        public $uid;
        public $status;
        public $remark;
        public $verificationCode;
        public $product;
    }

    class com_jpgk_catering_rpc_supplymarketing_AppointmentPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::Appointment', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::Appointment', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::Appointment';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_Appointment = IcePHP_declareClass('::com::jpgk::catering::rpc::supplymarketing::Appointment');
    $com_jpgk_catering_rpc_supplymarketing__t_AppointmentPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::supplymarketing::Appointment');

    $com_jpgk_catering_rpc_supplymarketing__t_Appointment = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::Appointment', 'com_jpgk_catering_rpc_supplymarketing_Appointment', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('name', $IcePHP__t_string, false, 0),
        array('appointmentTime', $IcePHP__t_int, false, 0),
        array('phone', $IcePHP__t_string, false, 0),
        array('productId', $IcePHP__t_int, false, 0),
        array('uid', $IcePHP__t_int, false, 0),
        array('status', $IcePHP__t_int, false, 0),
        array('remark', $IcePHP__t_string, false, 0),
        array('verificationCode', $IcePHP__t_string, false, 0),
        array('product', $com_jpgk_catering_rpc_supplymarketing__t_Product, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_AppointmentPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_Appointment);
}

global $com_jpgk_catering_rpc_supplymarketing__t_AppointmentStatus;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_AppointmentStatus'))
{
    class com_jpgk_catering_rpc_supplymarketing_AppointmentStatus
    {
        const ALL = 0;
        const ConfirmWaited = 1;
        const Completed = 2;
        const Cancelled = 3;
    }

    $com_jpgk_catering_rpc_supplymarketing__t_AppointmentStatus = IcePHP_defineEnum('::com::jpgk::catering::rpc::supplymarketing::AppointmentStatus', array('ALL', 0, 'ConfirmWaited', 1, 'Completed', 2, 'Cancelled', 3));
}

global $com_jpgk_catering_rpc_supplymarketing__t_AppointmentSeq;

if(!isset($com_jpgk_catering_rpc_supplymarketing__t_AppointmentSeq))
{
    $com_jpgk_catering_rpc_supplymarketing__t_AppointmentSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::supplymarketing::AppointmentSeq', $com_jpgk_catering_rpc_supplymarketing__t_Appointment);
}

global $com_jpgk_catering_rpc_supplymarketing__t_HotSearch;
global $com_jpgk_catering_rpc_supplymarketing__t_HotSearchPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_HotSearch'))
{
    class com_jpgk_catering_rpc_supplymarketing_HotSearch extends Ice_ObjectImpl
    {
        public function __construct($id=0, $name='')
        {
            $this->id = $id;
            $this->name = $name;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::HotSearch';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_HotSearch;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_HotSearch);
        }

        public $id;
        public $name;
    }

    class com_jpgk_catering_rpc_supplymarketing_HotSearchPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::HotSearch', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::HotSearch', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::HotSearch';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_HotSearch = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::HotSearch', 'com_jpgk_catering_rpc_supplymarketing_HotSearch', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('name', $IcePHP__t_string, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_HotSearchPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_HotSearch);
}

global $com_jpgk_catering_rpc_supplymarketing__t_HotSearchSeq;

if(!isset($com_jpgk_catering_rpc_supplymarketing__t_HotSearchSeq))
{
    $com_jpgk_catering_rpc_supplymarketing__t_HotSearchSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::supplymarketing::HotSearchSeq', $com_jpgk_catering_rpc_supplymarketing__t_HotSearch);
}

global $com_jpgk_catering_rpc_supplymarketing__t_ProductDetail;
global $com_jpgk_catering_rpc_supplymarketing__t_ProductDetailPrx;

if(!class_exists('com_jpgk_catering_rpc_supplymarketing_ProductDetail'))
{
    class com_jpgk_catering_rpc_supplymarketing_ProductDetail extends Ice_ObjectImpl
    {
        public function __construct($id=0, $title='', $description='', $isCollected=0, $isAppointed=0, $companyPhone='', $productH5Url='', $companyH5Url='')
        {
            $this->id = $id;
            $this->title = $title;
            $this->description = $description;
            $this->isCollected = $isCollected;
            $this->isAppointed = $isAppointed;
            $this->companyPhone = $companyPhone;
            $this->productH5Url = $productH5Url;
            $this->companyH5Url = $companyH5Url;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::ProductDetail';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_supplymarketing__t_ProductDetail;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_supplymarketing__t_ProductDetail);
        }

        public $id;
        public $title;
        public $description;
        public $isCollected;
        public $isAppointed;
        public $companyPhone;
        public $productH5Url;
        public $companyH5Url;
    }

    class com_jpgk_catering_rpc_supplymarketing_ProductDetailPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::supplymarketing::ProductDetail', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::supplymarketing::ProductDetail', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::supplymarketing::ProductDetail';
        }
    }

    $com_jpgk_catering_rpc_supplymarketing__t_ProductDetail = IcePHP_defineClass('::com::jpgk::catering::rpc::supplymarketing::ProductDetail', 'com_jpgk_catering_rpc_supplymarketing_ProductDetail', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('description', $IcePHP__t_string, false, 0),
        array('isCollected', $IcePHP__t_int, false, 0),
        array('isAppointed', $IcePHP__t_int, false, 0),
        array('companyPhone', $IcePHP__t_string, false, 0),
        array('productH5Url', $IcePHP__t_string, false, 0),
        array('companyH5Url', $IcePHP__t_string, false, 0)));

    $com_jpgk_catering_rpc_supplymarketing__t_ProductDetailPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_supplymarketing__t_ProductDetail);
}
?>
