<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `SecondMarketHandClass.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

require_once APP_PATH.'Common/Lib/Ice/BaseException.php';
require_once APP_PATH.'Common/Lib/Ice/BaseService.php';
require_once APP_PATH.'Common/Lib/Ice/Page.php';
require_once APP_PATH.'Common/Lib/Ice/common.php';

global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategory;
global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategoryPrx;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_GoodsCategory'))
{
    class com_jpgk_catering_rpc_secondhandmarket_GoodsCategory extends Ice_ObjectImpl
    {
        public function __construct($categoryId=0, $title='', $pId=0, $sort=0)
        {
            $this->categoryId = $categoryId;
            $this->title = $title;
            $this->pId = $pId;
            $this->sort = $sort;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::GoodsCategory';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategory;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategory);
        }

        public $categoryId;
        public $title;
        public $pId;
        public $sort;
    }

    class com_jpgk_catering_rpc_secondhandmarket_GoodsCategoryPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::GoodsCategory', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::GoodsCategory', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::GoodsCategory';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategory = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::GoodsCategory', 'com_jpgk_catering_rpc_secondhandmarket_GoodsCategory', -1, false, false, $Ice__t_Object, null, array(
        array('categoryId', $IcePHP__t_int, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('pId', $IcePHP__t_int, false, 0),
        array('sort', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategoryPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategory);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategorySeq;

if(!isset($com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategorySeq))
{
    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategorySeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::secondhandmarket::GoodsCategorySeq', $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategory);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_Goods;
global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsPrx;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_Goods'))
{
    class com_jpgk_catering_rpc_secondhandmarket_Goods extends Ice_ObjectImpl
    {
        public function __construct($goodsId=0, $title='', $description='', $goodsCategory=null, $salePrice=0.0, $boughtPrice=0.0, $view=0, $messageUserNum=0, $linkPhone='', $linkName='', $province=0, $city=0, $districtText='', $startTime=0, $endTime=0, $status=0, $checkStatus=0, $isCollected=0, $checkUid=0, $createTime=0, $showCreateTime='', $pictures=null, $isTop=0, $goodsStatus='')
        {
            $this->goodsId = $goodsId;
            $this->title = $title;
            $this->description = $description;
            $this->goodsCategory = $goodsCategory;
            $this->salePrice = $salePrice;
            $this->boughtPrice = $boughtPrice;
            $this->view = $view;
            $this->messageUserNum = $messageUserNum;
            $this->linkPhone = $linkPhone;
            $this->linkName = $linkName;
            $this->province = $province;
            $this->city = $city;
            $this->districtText = $districtText;
            $this->startTime = $startTime;
            $this->endTime = $endTime;
            $this->status = $status;
            $this->checkStatus = $checkStatus;
            $this->isCollected = $isCollected;
            $this->checkUid = $checkUid;
            $this->createTime = $createTime;
            $this->showCreateTime = $showCreateTime;
            $this->pictures = $pictures;
            $this->isTop = $isTop;
            $this->goodsStatus = $goodsStatus;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::Goods';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_secondhandmarket__t_Goods;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_secondhandmarket__t_Goods);
        }

        public $goodsId;
        public $title;
        public $description;
        public $goodsCategory;
        public $salePrice;
        public $boughtPrice;
        public $view;
        public $messageUserNum;
        public $linkPhone;
        public $linkName;
        public $province;
        public $city;
        public $districtText;
        public $startTime;
        public $endTime;
        public $status;
        public $checkStatus;
        public $isCollected;
        public $checkUid;
        public $createTime;
        public $showCreateTime;
        public $pictures;
        public $isTop;
        public $goodsStatus;
    }

    class com_jpgk_catering_rpc_secondhandmarket_GoodsPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::Goods', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::Goods', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::Goods';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_Goods = IcePHP_declareClass('::com::jpgk::catering::rpc::secondhandmarket::Goods');
    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::secondhandmarket::Goods');

    $com_jpgk_catering_rpc_secondhandmarket__t_Goods = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::Goods', 'com_jpgk_catering_rpc_secondhandmarket_Goods', -1, false, false, $Ice__t_Object, null, array(
        array('goodsId', $IcePHP__t_int, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('description', $IcePHP__t_string, false, 0),
        array('goodsCategory', $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategory, false, 0),
        array('salePrice', $IcePHP__t_double, false, 0),
        array('boughtPrice', $IcePHP__t_double, false, 0),
        array('view', $IcePHP__t_int, false, 0),
        array('messageUserNum', $IcePHP__t_int, false, 0),
        array('linkPhone', $IcePHP__t_string, false, 0),
        array('linkName', $IcePHP__t_string, false, 0),
        array('province', $IcePHP__t_int, false, 0),
        array('city', $IcePHP__t_int, false, 0),
        array('districtText', $IcePHP__t_string, false, 0),
        array('startTime', $IcePHP__t_int, false, 0),
        array('endTime', $IcePHP__t_int, false, 0),
        array('status', $IcePHP__t_int, false, 0),
        array('checkStatus', $IcePHP__t_int, false, 0),
        array('isCollected', $IcePHP__t_int, false, 0),
        array('checkUid', $IcePHP__t_int, false, 0),
        array('createTime', $IcePHP__t_int, false, 0),
        array('showCreateTime', $IcePHP__t_string, false, 0),
        array('pictures', $com_jpgk_catering_rpc_common__t_PictureSeq, false, 0),
        array('isTop', $IcePHP__t_int, false, 0),
        array('goodsStatus', $IcePHP__t_string, false, 0)));

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_Goods);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSeq;

if(!isset($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSeq))
{
    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::secondhandmarket::GoodsSeq', $com_jpgk_catering_rpc_secondhandmarket__t_Goods);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSort;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_GoodsSort'))
{
    class com_jpgk_catering_rpc_secondhandmarket_GoodsSort
    {
        const Integrated = 0;
        const Newest = 1;
        const HighestPrice = 2;
        const LowestPrice = 3;
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSort = IcePHP_defineEnum('::com::jpgk::catering::rpc::secondhandmarket::GoodsSort', array('Integrated', 0, 'Newest', 1, 'HighestPrice', 2, 'LowestPrice', 3));
}

global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModel;
global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModelPrx;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_GoodsSaveModel'))
{
    class com_jpgk_catering_rpc_secondhandmarket_GoodsSaveModel extends Ice_ObjectImpl
    {
        public function __construct($goodsId=0, $uid=0, $title='', $description='', $categoryId=0, $salePrice=0.0, $boughtPrice=0.0, $linkPhone='', $linkName='', $province=0, $city=0, $districtText='', $startTime=0, $endTime=0, $pictures=null)
        {
            $this->goodsId = $goodsId;
            $this->uid = $uid;
            $this->title = $title;
            $this->description = $description;
            $this->categoryId = $categoryId;
            $this->salePrice = $salePrice;
            $this->boughtPrice = $boughtPrice;
            $this->linkPhone = $linkPhone;
            $this->linkName = $linkName;
            $this->province = $province;
            $this->city = $city;
            $this->districtText = $districtText;
            $this->startTime = $startTime;
            $this->endTime = $endTime;
            $this->pictures = $pictures;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::GoodsSaveModel';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModel;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModel);
        }

        public $goodsId;
        public $uid;
        public $title;
        public $description;
        public $categoryId;
        public $salePrice;
        public $boughtPrice;
        public $linkPhone;
        public $linkName;
        public $province;
        public $city;
        public $districtText;
        public $startTime;
        public $endTime;
        public $pictures;
    }

    class com_jpgk_catering_rpc_secondhandmarket_GoodsSaveModelPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::GoodsSaveModel', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::GoodsSaveModel', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::GoodsSaveModel';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModel = IcePHP_declareClass('::com::jpgk::catering::rpc::secondhandmarket::GoodsSaveModel');
    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModelPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::secondhandmarket::GoodsSaveModel');

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModel = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::GoodsSaveModel', 'com_jpgk_catering_rpc_secondhandmarket_GoodsSaveModel', -1, false, false, $Ice__t_Object, null, array(
        array('goodsId', $IcePHP__t_int, false, 0),
        array('uid', $IcePHP__t_int, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('description', $IcePHP__t_string, false, 0),
        array('categoryId', $IcePHP__t_int, false, 0),
        array('salePrice', $IcePHP__t_double, false, 0),
        array('boughtPrice', $IcePHP__t_double, false, 0),
        array('linkPhone', $IcePHP__t_string, false, 0),
        array('linkName', $IcePHP__t_string, false, 0),
        array('province', $IcePHP__t_int, false, 0),
        array('city', $IcePHP__t_int, false, 0),
        array('districtText', $IcePHP__t_string, false, 0),
        array('startTime', $IcePHP__t_int, false, 0),
        array('endTime', $IcePHP__t_int, false, 0),
        array('pictures', $com_jpgk_catering_rpc_common__t_PictureSeq, false, 0)));

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModelPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_GoodsSaveModel);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetail;
global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetailPrx;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_GoodsDetail'))
{
    class com_jpgk_catering_rpc_secondhandmarket_GoodsDetail extends Ice_ObjectImpl
    {
        public function __construct($goodsId=0, $title='', $description='', $linkPhone='', $linkName='', $isCollected=0, $h5Url='', $status=0, $districtText='', $goodsCategory=null, $salePrice=0.0, $boughtPrice=0.0, $pictures=null, $province=0, $city=0)
        {
            $this->goodsId = $goodsId;
            $this->title = $title;
            $this->description = $description;
            $this->linkPhone = $linkPhone;
            $this->linkName = $linkName;
            $this->isCollected = $isCollected;
            $this->h5Url = $h5Url;
            $this->status = $status;
            $this->districtText = $districtText;
            $this->goodsCategory = $goodsCategory;
            $this->salePrice = $salePrice;
            $this->boughtPrice = $boughtPrice;
            $this->pictures = $pictures;
            $this->province = $province;
            $this->city = $city;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::GoodsDetail';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetail;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetail);
        }

        public $goodsId;
        public $title;
        public $description;
        public $linkPhone;
        public $linkName;
        public $isCollected;
        public $h5Url;
        public $status;
        public $districtText;
        public $goodsCategory;
        public $salePrice;
        public $boughtPrice;
        public $pictures;
        public $province;
        public $city;
    }

    class com_jpgk_catering_rpc_secondhandmarket_GoodsDetailPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::GoodsDetail', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::GoodsDetail', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::GoodsDetail';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetail = IcePHP_declareClass('::com::jpgk::catering::rpc::secondhandmarket::GoodsDetail');
    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetailPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::secondhandmarket::GoodsDetail');

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetail = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::GoodsDetail', 'com_jpgk_catering_rpc_secondhandmarket_GoodsDetail', -1, false, false, $Ice__t_Object, null, array(
        array('goodsId', $IcePHP__t_int, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('description', $IcePHP__t_string, false, 0),
        array('linkPhone', $IcePHP__t_string, false, 0),
        array('linkName', $IcePHP__t_string, false, 0),
        array('isCollected', $IcePHP__t_int, false, 0),
        array('h5Url', $IcePHP__t_string, false, 0),
        array('status', $IcePHP__t_int, false, 0),
        array('districtText', $IcePHP__t_string, false, 0),
        array('goodsCategory', $com_jpgk_catering_rpc_secondhandmarket__t_GoodsCategory, false, 0),
        array('salePrice', $IcePHP__t_double, false, 0),
        array('boughtPrice', $IcePHP__t_double, false, 0),
        array('pictures', $com_jpgk_catering_rpc_common__t_PictureSeq, false, 0),
        array('province', $IcePHP__t_int, false, 0),
        array('city', $IcePHP__t_int, false, 0)));

    $com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetailPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_GoodsDetail);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoods;
global $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoodsPrx;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_OrderGoods'))
{
    class com_jpgk_catering_rpc_secondhandmarket_OrderGoods extends com_jpgk_catering_rpc_secondhandmarket_Goods
    {
        public function __construct($goodsId=0, $title='', $description='', $goodsCategory=null, $salePrice=0.0, $boughtPrice=0.0, $view=0, $messageUserNum=0, $linkPhone='', $linkName='', $province=0, $city=0, $districtText='', $startTime=0, $endTime=0, $status=0, $checkStatus=0, $isCollected=0, $checkUid=0, $createTime=0, $showCreateTime='', $pictures=null, $isTop=0, $goodsStatus='', $goodsNum=0, $isMaintenance=0, $goodsMoney=0.0, $deliveryMoney=0.0, $maintenanceMoney=0.0)
        {
            parent::__construct($goodsId, $title, $description, $goodsCategory, $salePrice, $boughtPrice, $view, $messageUserNum, $linkPhone, $linkName, $province, $city, $districtText, $startTime, $endTime, $status, $checkStatus, $isCollected, $checkUid, $createTime, $showCreateTime, $pictures, $isTop, $goodsStatus);
            $this->goodsNum = $goodsNum;
            $this->isMaintenance = $isMaintenance;
            $this->goodsMoney = $goodsMoney;
            $this->deliveryMoney = $deliveryMoney;
            $this->maintenanceMoney = $maintenanceMoney;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::OrderGoods';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoods;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoods);
        }

        public $goodsNum;
        public $isMaintenance;
        public $goodsMoney;
        public $deliveryMoney;
        public $maintenanceMoney;
    }

    class com_jpgk_catering_rpc_secondhandmarket_OrderGoodsPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::OrderGoods', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::OrderGoods', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::OrderGoods';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoods = IcePHP_declareClass('::com::jpgk::catering::rpc::secondhandmarket::OrderGoods');
    $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoodsPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::secondhandmarket::OrderGoods');

    $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoods = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::OrderGoods', 'com_jpgk_catering_rpc_secondhandmarket_OrderGoods', -1, false, false, $com_jpgk_catering_rpc_secondhandmarket__t_Goods, null, array(
        array('goodsNum', $IcePHP__t_int, false, 0),
        array('isMaintenance', $IcePHP__t_int, false, 0),
        array('goodsMoney', $IcePHP__t_double, false, 0),
        array('deliveryMoney', $IcePHP__t_double, false, 0),
        array('maintenanceMoney', $IcePHP__t_double, false, 0)));

    $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoodsPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_OrderGoods);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoodsSeq;

if(!isset($com_jpgk_catering_rpc_secondhandmarket__t_OrderGoodsSeq))
{
    $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoodsSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::secondhandmarket::OrderGoodsSeq', $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoods);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_Order;
global $com_jpgk_catering_rpc_secondhandmarket__t_OrderPrx;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_Order'))
{
    class com_jpgk_catering_rpc_secondhandmarket_Order extends com_jpgk_common_rpc_ResponseModelClass
    {
        public function __construct($success=false, $status=0, $msg='', $id=0, $orderCode='', $orderState=0, $orderStateDesc='', $uid=0, $payType=0, $goodsMoneyTotal=0.0, $goodsDeliveryTotal=0.0, $moneyTotal=0.0, $createTime='', $remark='', $orderGoodses=null, $leftTime=0, $deliveryAddress=null)
        {
            parent::__construct($success, $status, $msg);
            $this->id = $id;
            $this->orderCode = $orderCode;
            $this->orderState = $orderState;
            $this->orderStateDesc = $orderStateDesc;
            $this->uid = $uid;
            $this->payType = $payType;
            $this->goodsMoneyTotal = $goodsMoneyTotal;
            $this->goodsDeliveryTotal = $goodsDeliveryTotal;
            $this->moneyTotal = $moneyTotal;
            $this->createTime = $createTime;
            $this->remark = $remark;
            $this->orderGoodses = $orderGoodses;
            $this->leftTime = $leftTime;
            $this->deliveryAddress = $deliveryAddress;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::Order';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_secondhandmarket__t_Order;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_secondhandmarket__t_Order);
        }

        public $id;
        public $orderCode;
        public $orderState;
        public $orderStateDesc;
        public $uid;
        public $payType;
        public $goodsMoneyTotal;
        public $goodsDeliveryTotal;
        public $moneyTotal;
        public $createTime;
        public $remark;
        public $orderGoodses;
        public $leftTime;
        public $deliveryAddress;
    }

    class com_jpgk_catering_rpc_secondhandmarket_OrderPrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::Order', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::Order', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::Order';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_Order = IcePHP_declareClass('::com::jpgk::catering::rpc::secondhandmarket::Order');
    $com_jpgk_catering_rpc_secondhandmarket__t_OrderPrx = IcePHP_declareProxy('::com::jpgk::catering::rpc::secondhandmarket::Order');

    $com_jpgk_catering_rpc_secondhandmarket__t_Order = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::Order', 'com_jpgk_catering_rpc_secondhandmarket_Order', -1, false, false, $com_jpgk_common_rpc__t_ResponseModelClass, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('orderCode', $IcePHP__t_string, false, 0),
        array('orderState', $IcePHP__t_int, false, 0),
        array('orderStateDesc', $IcePHP__t_string, false, 0),
        array('uid', $IcePHP__t_int, false, 0),
        array('payType', $IcePHP__t_int, false, 0),
        array('goodsMoneyTotal', $IcePHP__t_double, false, 0),
        array('goodsDeliveryTotal', $IcePHP__t_double, false, 0),
        array('moneyTotal', $IcePHP__t_double, false, 0),
        array('createTime', $IcePHP__t_string, false, 0),
        array('remark', $IcePHP__t_string, false, 0),
        array('orderGoodses', $com_jpgk_catering_rpc_secondhandmarket__t_OrderGoodsSeq, false, 0),
        array('leftTime', $IcePHP__t_int, false, 0),
        array('deliveryAddress', $com_jpgk_catering_rpc_common__t_DeliveryAddress, false, 0)));

    $com_jpgk_catering_rpc_secondhandmarket__t_OrderPrx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_Order);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_OrderSeq;

if(!isset($com_jpgk_catering_rpc_secondhandmarket__t_OrderSeq))
{
    $com_jpgk_catering_rpc_secondhandmarket__t_OrderSeq = IcePHP_defineSequence('::com::jpgk::catering::rpc::secondhandmarket::OrderSeq', $com_jpgk_catering_rpc_secondhandmarket__t_Order);
}

global $com_jpgk_catering_rpc_secondhandmarket__t_OrderStatus;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_OrderStatus'))
{
    class com_jpgk_catering_rpc_secondhandmarket_OrderStatus
    {
        const All = 0;
        const PayWaiting = 1;
        const ReceiveWaiting = 2;
        const Completed = 3;
        const Cancelled = 4;
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_OrderStatus = IcePHP_defineEnum('::com::jpgk::catering::rpc::secondhandmarket::OrderStatus', array('All', 0, 'PayWaiting', 1, 'ReceiveWaiting', 2, 'Completed', 3, 'Cancelled', 4));
}

global $com_jpgk_catering_rpc_secondhandmarket__t_Maintenance;
global $com_jpgk_catering_rpc_secondhandmarket__t_MaintenancePrx;

if(!class_exists('com_jpgk_catering_rpc_secondhandmarket_Maintenance'))
{
    class com_jpgk_catering_rpc_secondhandmarket_Maintenance extends Ice_ObjectImpl
    {
        public function __construct($id=0, $title='', $timeLimit='', $money=0.0, $description='')
        {
            $this->id = $id;
            $this->title = $title;
            $this->timeLimit = $timeLimit;
            $this->money = $money;
            $this->description = $description;
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::Maintenance';
        }

        public function __toString()
        {
            global $com_jpgk_catering_rpc_secondhandmarket__t_Maintenance;
            return IcePHP_stringify($this, $com_jpgk_catering_rpc_secondhandmarket__t_Maintenance);
        }

        public $id;
        public $title;
        public $timeLimit;
        public $money;
        public $description;
    }

    class com_jpgk_catering_rpc_secondhandmarket_MaintenancePrxHelper
    {
        public static function checkedCast($proxy, $facetOrCtx=null, $ctx=null)
        {
            return $proxy->ice_checkedCast('::com::jpgk::catering::rpc::secondhandmarket::Maintenance', $facetOrCtx, $ctx);
        }

        public static function uncheckedCast($proxy, $facet=null)
        {
            return $proxy->ice_uncheckedCast('::com::jpgk::catering::rpc::secondhandmarket::Maintenance', $facet);
        }

        public static function ice_staticId()
        {
            return '::com::jpgk::catering::rpc::secondhandmarket::Maintenance';
        }
    }

    $com_jpgk_catering_rpc_secondhandmarket__t_Maintenance = IcePHP_defineClass('::com::jpgk::catering::rpc::secondhandmarket::Maintenance', 'com_jpgk_catering_rpc_secondhandmarket_Maintenance', -1, false, false, $Ice__t_Object, null, array(
        array('id', $IcePHP__t_int, false, 0),
        array('title', $IcePHP__t_string, false, 0),
        array('timeLimit', $IcePHP__t_string, false, 0),
        array('money', $IcePHP__t_double, false, 0),
        array('description', $IcePHP__t_string, false, 0)));

    $com_jpgk_catering_rpc_secondhandmarket__t_MaintenancePrx = IcePHP_defineProxy($com_jpgk_catering_rpc_secondhandmarket__t_Maintenance);
}
?>
