<?php
// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `ErrorCode.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


global $com_jpgk_common_rpc__t_ErrorCode;

if(!class_exists('com_jpgk_common_rpc_ErrorCode'))
{
    class com_jpgk_common_rpc_ErrorCode
    {
        const REQUESTNOPASS = 5101;
        const REQUESTUSERNAMENULL = 5102;
        const REQUESTUSERTOKENNULL = 5103;
    }

    $com_jpgk_common_rpc__t_ErrorCode = IcePHP_defineEnum('::com::jpgk::common::rpc::ErrorCode', array('REQUESTNOPASS', 5101, 'REQUESTUSERNAMENULL', 5102, 'REQUESTUSERTOKENNULL', 5103));
}
?>
